"""webhook service schema

Revision ID: 73adab851faf
Revises: 
Create Date: 2026-08-06 17:27:07.976058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73adab851faf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_audit',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_audit_action', 'webhook_audit', ['action'], unique=False)
    op.create_index(op.f('ix_webhook_audit_entity_id'), 'webhook_audit', ['entity_id'], unique=False)
    op.create_index('ix_webhook_audit_occurred_at', 'webhook_audit', ['occurred_at'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('auth_method', sa.String(length=32), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('timeout_seconds', sa.Float(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('backoff_strategy', sa.String(length=16), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_endpoint_org_status', 'webhook_endpoints', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_kind'), 'webhook_endpoints', ['kind'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_status'), 'webhook_endpoints', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_event_org_type', 'webhook_events', ['organization_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_correlation_id'), 'webhook_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_idempotency_key'), 'webhook_events', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_webhook_events_kind'), 'webhook_events', ['kind'], unique=False)
    op.create_index(op.f('ix_webhook_events_source'), 'webhook_events', ['source'], unique=False)
    op.create_table('webhook_idempotency',
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response_snapshot', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_webhook_idempotency_key')
    )
    op.create_index('ix_webhook_idempotency_expires_at', 'webhook_idempotency', ['expires_at'], unique=False)
    op.create_index(op.f('ix_webhook_idempotency_status'), 'webhook_idempotency', ['status'], unique=False)
    op.create_table('webhook_reports',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_reports_kind'), 'webhook_reports', ['kind'], unique=False)
    op.create_table('webhook_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('events_received', sa.Integer(), nullable=False),
    sa.Column('deliveries_attempted', sa.Integer(), nullable=False),
    sa.Column('deliveries_succeeded', sa.Integer(), nullable=False),
    sa.Column('deliveries_failed', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('replays', sa.Integer(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('by_endpoint', sa.JSON(), nullable=False),
    sa.Column('by_event_type', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_statistics_window_start', 'webhook_statistics', ['window_start'], unique=False)
    op.create_table('webhook_signatures',
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('secret_version', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=16), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_signature_endpoint_version', 'webhook_signatures', ['endpoint_id', 'secret_version'], unique=True)
    op.create_index(op.f('ix_webhook_signatures_endpoint_id'), 'webhook_signatures', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_signatures_status'), 'webhook_signatures', ['status'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_reference', sa.String(length=255), nullable=True),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('condition_expression', sa.String(length=1024), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_subscription_org_scope', 'webhook_subscriptions', ['organization_id', 'scope'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_endpoint_id'), 'webhook_subscriptions', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_scope'), 'webhook_subscriptions', ['scope'], unique=False)
    op.create_table('webhook_transformations',
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_transformation_endpoint', 'webhook_transformations', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_transformations_endpoint_id'), 'webhook_transformations', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_transformations_kind'), 'webhook_transformations', ['kind'], unique=False)
    op.create_table('webhook_filters',
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('match_mode', sa.String(length=8), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_filter_subscription', 'webhook_filters', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_webhook_filters_subscription_id'), 'webhook_filters', ['subscription_id'], unique=False)
    op.create_table('webhook_replay_jobs',
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('endpoint_id', sa.Uuid(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('replayed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['webhook_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_replay_jobs_status'), 'webhook_replay_jobs', ['status'], unique=False)
    op.create_index('ix_webhook_replay_org_status', 'webhook_replay_jobs', ['organization_id', 'status'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('replay_job_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['webhook_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replay_job_id'], ['webhook_replay_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_endpoint_id'), 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_event_id'), 'webhook_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_idempotency_key'), 'webhook_deliveries', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_index('ix_webhook_delivery_endpoint', 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index('ix_webhook_delivery_org_status', 'webhook_deliveries', ['organization_id', 'status'], unique=False)
    op.create_table('webhook_dead_letters',
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replayed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['webhook_deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_dead_letter_org', 'webhook_dead_letters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_dead_letters_delivery_id'), 'webhook_dead_letters', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_webhook_dead_letters_endpoint_id'), 'webhook_dead_letters', ['endpoint_id'], unique=False)
    op.create_table('webhook_delivery_attempts',
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['webhook_deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_attempt_delivery', 'webhook_delivery_attempts', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_attempts_delivery_id'), 'webhook_delivery_attempts', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_attempts_endpoint_id'), 'webhook_delivery_attempts', ['endpoint_id'], unique=False)
    op.create_table('webhook_retry_queue',
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('backoff_strategy', sa.String(length=16), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['webhook_deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_retry_due', 'webhook_retry_queue', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_webhook_retry_queue_delivery_id'), 'webhook_retry_queue', ['delivery_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_retry_queue_delivery_id'), table_name='webhook_retry_queue')
    op.drop_index('ix_webhook_retry_due', table_name='webhook_retry_queue')
    op.drop_table('webhook_retry_queue')
    op.drop_index(op.f('ix_webhook_delivery_attempts_delivery_id'), table_name='webhook_delivery_attempts')
    op.drop_index('ix_webhook_attempt_delivery', table_name='webhook_delivery_attempts')
    op.drop_table('webhook_delivery_attempts')
    op.drop_index(op.f('ix_webhook_dead_letters_endpoint_id'), table_name='webhook_dead_letters')
    op.drop_index(op.f('ix_webhook_dead_letters_delivery_id'), table_name='webhook_dead_letters')
    op.drop_index('ix_webhook_dead_letter_org', table_name='webhook_dead_letters')
    op.drop_table('webhook_dead_letters')
    op.drop_index('ix_webhook_delivery_org_status', table_name='webhook_deliveries')
    op.drop_index('ix_webhook_delivery_endpoint', table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_idempotency_key'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index('ix_webhook_replay_org_status', table_name='webhook_replay_jobs')
    op.drop_index(op.f('ix_webhook_replay_jobs_status'), table_name='webhook_replay_jobs')
    op.drop_table('webhook_replay_jobs')
    op.drop_index(op.f('ix_webhook_filters_subscription_id'), table_name='webhook_filters')
    op.drop_index('ix_webhook_filter_subscription', table_name='webhook_filters')
    op.drop_table('webhook_filters')
    op.drop_index(op.f('ix_webhook_transformations_kind'), table_name='webhook_transformations')
    op.drop_index(op.f('ix_webhook_transformations_endpoint_id'), table_name='webhook_transformations')
    op.drop_index('ix_webhook_transformation_endpoint', table_name='webhook_transformations')
    op.drop_table('webhook_transformations')
    op.drop_index(op.f('ix_webhook_subscriptions_scope'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_endpoint_id'), table_name='webhook_subscriptions')
    op.drop_index('ix_webhook_subscription_org_scope', table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_signatures_status'), table_name='webhook_signatures')
    op.drop_index(op.f('ix_webhook_signatures_endpoint_id'), table_name='webhook_signatures')
    op.drop_index('ix_webhook_signature_endpoint_version', table_name='webhook_signatures')
    op.drop_table('webhook_signatures')
    op.drop_index('ix_webhook_statistics_window_start', table_name='webhook_statistics')
    op.drop_table('webhook_statistics')
    op.drop_index(op.f('ix_webhook_reports_kind'), table_name='webhook_reports')
    op.drop_table('webhook_reports')
    op.drop_index(op.f('ix_webhook_idempotency_status'), table_name='webhook_idempotency')
    op.drop_index('ix_webhook_idempotency_expires_at', table_name='webhook_idempotency')
    op.drop_table('webhook_idempotency')
    op.drop_index(op.f('ix_webhook_events_source'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_kind'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_idempotency_key'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_correlation_id'), table_name='webhook_events')
    op.drop_index('ix_webhook_event_org_type', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_webhook_endpoints_status'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_kind'), table_name='webhook_endpoints')
    op.drop_index('ix_webhook_endpoint_org_status', table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index('ix_webhook_audit_occurred_at', table_name='webhook_audit')
    op.drop_index(op.f('ix_webhook_audit_entity_id'), table_name='webhook_audit')
    op.drop_index('ix_webhook_audit_action', table_name='webhook_audit')
    op.drop_table('webhook_audit')
    # ### end Alembic commands ###
