"""initial monitoring schema

Revision ID: 7aa9f8dafbeb
Revises: 
Create Date: 2026-07-27 20:00:54.421104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa9f8dafbeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_audit',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_collectors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('collector_key', sa.String(length=64), nullable=False),
    sa.Column('target_types', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('interval_seconds', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_collectors_collector_key'), 'monitoring_collectors', ['collector_key'], unique=False)
    op.create_index(op.f('ix_monitoring_collectors_name'), 'monitoring_collectors', ['name'], unique=False)
    op.create_table('monitoring_retention',
    sa.Column('metric_type', sa.String(length=24), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('downsampling_function', sa.String(length=8), nullable=True),
    sa.Column('downsampling_interval_seconds', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_retention_metric_type'), 'monitoring_retention', ['metric_type'], unique=False)
    op.create_table('monitoring_statistics',
    sa.Column('total_targets', sa.Integer(), nullable=False),
    sa.Column('total_metrics_collected', sa.Integer(), nullable=False),
    sa.Column('average_availability_percentage', sa.Float(), nullable=False),
    sa.Column('average_health_score', sa.Float(), nullable=False),
    sa.Column('sla_compliance_percentage', sa.Float(), nullable=False),
    sa.Column('slo_compliance_percentage', sa.Float(), nullable=False),
    sa.Column('top_threshold_breaches', sa.JSON(), nullable=False),
    sa.Column('trend_data', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_targets',
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_targets_external_id'), 'monitoring_targets', ['external_id'], unique=False)
    op.create_index(op.f('ix_monitoring_targets_name'), 'monitoring_targets', ['name'], unique=False)
    op.create_index(op.f('ix_monitoring_targets_target_type'), 'monitoring_targets', ['target_type'], unique=False)
    op.create_table('monitoring_availability',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_availability_started_at'), 'monitoring_availability', ['started_at'], unique=False)
    op.create_index(op.f('ix_monitoring_availability_status'), 'monitoring_availability', ['status'], unique=False)
    op.create_index(op.f('ix_monitoring_availability_target_id'), 'monitoring_availability', ['target_id'], unique=False)
    op.create_table('monitoring_dependencies',
    sa.Column('parent_target_id', sa.Uuid(), nullable=False),
    sa.Column('child_target_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_type', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['child_target_id'], ['monitoring_targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_target_id'], ['monitoring_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_dependencies_child_target_id'), 'monitoring_dependencies', ['child_target_id'], unique=False)
    op.create_index(op.f('ix_monitoring_dependencies_dependency_type'), 'monitoring_dependencies', ['dependency_type'], unique=False)
    op.create_index(op.f('ix_monitoring_dependencies_parent_target_id'), 'monitoring_dependencies', ['parent_target_id'], unique=False)
    op.create_table('monitoring_health',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('check_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_health_check_type'), 'monitoring_health', ['check_type'], unique=False)
    op.create_index(op.f('ix_monitoring_health_checked_at'), 'monitoring_health', ['checked_at'], unique=False)
    op.create_index(op.f('ix_monitoring_health_status'), 'monitoring_health', ['status'], unique=False)
    op.create_index(op.f('ix_monitoring_health_target_id'), 'monitoring_health', ['target_id'], unique=False)
    op.create_table('monitoring_history',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_history_recorded_at'), 'monitoring_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_monitoring_history_status'), 'monitoring_history', ['status'], unique=False)
    op.create_index(op.f('ix_monitoring_history_target_id'), 'monitoring_history', ['target_id'], unique=False)
    op.create_table('monitoring_metrics',
    sa.Column('collector_id', sa.Uuid(), nullable=True),
    sa.Column('metric_type', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['monitoring_collectors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_metrics_collector_id'), 'monitoring_metrics', ['collector_id'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_metric_type'), 'monitoring_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_name'), 'monitoring_metrics', ['name'], unique=False)
    op.create_table('monitoring_reports',
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('report_type', sa.String(length=16), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_reports_report_type'), 'monitoring_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_monitoring_reports_target_id'), 'monitoring_reports', ['target_id'], unique=False)
    op.create_table('monitoring_sla',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('sla_type', sa.String(length=16), nullable=False),
    sa.Column('objective_percentage', sa.Float(), nullable=False),
    sa.Column('actual_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_sla_sla_type'), 'monitoring_sla', ['sla_type'], unique=False)
    op.create_index(op.f('ix_monitoring_sla_status'), 'monitoring_sla', ['status'], unique=False)
    op.create_index(op.f('ix_monitoring_sla_target_id'), 'monitoring_sla', ['target_id'], unique=False)
    op.create_table('monitoring_slo',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('slo_type', sa.String(length=16), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('error_budget_remaining_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_slo_slo_type'), 'monitoring_slo', ['slo_type'], unique=False)
    op.create_index(op.f('ix_monitoring_slo_status'), 'monitoring_slo', ['status'], unique=False)
    op.create_index(op.f('ix_monitoring_slo_target_id'), 'monitoring_slo', ['target_id'], unique=False)
    op.create_table('monitoring_synthetic_tests',
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('check_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('interval_seconds', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_synthetic_tests_check_type'), 'monitoring_synthetic_tests', ['check_type'], unique=False)
    op.create_index(op.f('ix_monitoring_synthetic_tests_name'), 'monitoring_synthetic_tests', ['name'], unique=False)
    op.create_index(op.f('ix_monitoring_synthetic_tests_target_id'), 'monitoring_synthetic_tests', ['target_id'], unique=False)
    op.create_table('monitoring_metric_series',
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['monitoring_metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_metric_series_metric_id'), 'monitoring_metric_series', ['metric_id'], unique=False)
    op.create_index(op.f('ix_monitoring_metric_series_recorded_at'), 'monitoring_metric_series', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_monitoring_metric_series_target_id'), 'monitoring_metric_series', ['target_id'], unique=False)
    op.create_table('monitoring_rules',
    sa.Column('metric_id', sa.Uuid(), nullable=True),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('window_seconds', sa.Float(), nullable=True),
    sa.Column('escalation_after_seconds', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['monitoring_metrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_rules_metric_id'), 'monitoring_rules', ['metric_id'], unique=False)
    op.create_index(op.f('ix_monitoring_rules_name'), 'monitoring_rules', ['name'], unique=False)
    op.create_index(op.f('ix_monitoring_rules_rule_type'), 'monitoring_rules', ['rule_type'], unique=False)
    op.create_table('monitoring_thresholds',
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('threshold_type', sa.String(length=16), nullable=False),
    sa.Column('informational', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('medium', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('critical', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['monitoring_metrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_thresholds_metric_id'), 'monitoring_thresholds', ['metric_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_thresholds_metric_id'), table_name='monitoring_thresholds')
    op.drop_table('monitoring_thresholds')
    op.drop_index(op.f('ix_monitoring_rules_rule_type'), table_name='monitoring_rules')
    op.drop_index(op.f('ix_monitoring_rules_name'), table_name='monitoring_rules')
    op.drop_index(op.f('ix_monitoring_rules_metric_id'), table_name='monitoring_rules')
    op.drop_table('monitoring_rules')
    op.drop_index(op.f('ix_monitoring_metric_series_target_id'), table_name='monitoring_metric_series')
    op.drop_index(op.f('ix_monitoring_metric_series_recorded_at'), table_name='monitoring_metric_series')
    op.drop_index(op.f('ix_monitoring_metric_series_metric_id'), table_name='monitoring_metric_series')
    op.drop_table('monitoring_metric_series')
    op.drop_index(op.f('ix_monitoring_synthetic_tests_target_id'), table_name='monitoring_synthetic_tests')
    op.drop_index(op.f('ix_monitoring_synthetic_tests_name'), table_name='monitoring_synthetic_tests')
    op.drop_index(op.f('ix_monitoring_synthetic_tests_check_type'), table_name='monitoring_synthetic_tests')
    op.drop_table('monitoring_synthetic_tests')
    op.drop_index(op.f('ix_monitoring_slo_target_id'), table_name='monitoring_slo')
    op.drop_index(op.f('ix_monitoring_slo_status'), table_name='monitoring_slo')
    op.drop_index(op.f('ix_monitoring_slo_slo_type'), table_name='monitoring_slo')
    op.drop_table('monitoring_slo')
    op.drop_index(op.f('ix_monitoring_sla_target_id'), table_name='monitoring_sla')
    op.drop_index(op.f('ix_monitoring_sla_status'), table_name='monitoring_sla')
    op.drop_index(op.f('ix_monitoring_sla_sla_type'), table_name='monitoring_sla')
    op.drop_table('monitoring_sla')
    op.drop_index(op.f('ix_monitoring_reports_target_id'), table_name='monitoring_reports')
    op.drop_index(op.f('ix_monitoring_reports_report_type'), table_name='monitoring_reports')
    op.drop_table('monitoring_reports')
    op.drop_index(op.f('ix_monitoring_metrics_name'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_metric_type'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_collector_id'), table_name='monitoring_metrics')
    op.drop_table('monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_history_target_id'), table_name='monitoring_history')
    op.drop_index(op.f('ix_monitoring_history_status'), table_name='monitoring_history')
    op.drop_index(op.f('ix_monitoring_history_recorded_at'), table_name='monitoring_history')
    op.drop_table('monitoring_history')
    op.drop_index(op.f('ix_monitoring_health_target_id'), table_name='monitoring_health')
    op.drop_index(op.f('ix_monitoring_health_status'), table_name='monitoring_health')
    op.drop_index(op.f('ix_monitoring_health_checked_at'), table_name='monitoring_health')
    op.drop_index(op.f('ix_monitoring_health_check_type'), table_name='monitoring_health')
    op.drop_table('monitoring_health')
    op.drop_index(op.f('ix_monitoring_dependencies_parent_target_id'), table_name='monitoring_dependencies')
    op.drop_index(op.f('ix_monitoring_dependencies_dependency_type'), table_name='monitoring_dependencies')
    op.drop_index(op.f('ix_monitoring_dependencies_child_target_id'), table_name='monitoring_dependencies')
    op.drop_table('monitoring_dependencies')
    op.drop_index(op.f('ix_monitoring_availability_target_id'), table_name='monitoring_availability')
    op.drop_index(op.f('ix_monitoring_availability_status'), table_name='monitoring_availability')
    op.drop_index(op.f('ix_monitoring_availability_started_at'), table_name='monitoring_availability')
    op.drop_table('monitoring_availability')
    op.drop_index(op.f('ix_monitoring_targets_target_type'), table_name='monitoring_targets')
    op.drop_index(op.f('ix_monitoring_targets_name'), table_name='monitoring_targets')
    op.drop_index(op.f('ix_monitoring_targets_external_id'), table_name='monitoring_targets')
    op.drop_table('monitoring_targets')
    op.drop_table('monitoring_statistics')
    op.drop_index(op.f('ix_monitoring_retention_metric_type'), table_name='monitoring_retention')
    op.drop_table('monitoring_retention')
    op.drop_index(op.f('ix_monitoring_collectors_name'), table_name='monitoring_collectors')
    op.drop_index(op.f('ix_monitoring_collectors_collector_key'), table_name='monitoring_collectors')
    op.drop_table('monitoring_collectors')
    op.drop_table('monitoring_audit')
    # ### end Alembic commands ###
