"""initial knowledge graph schema

Revision ID: 9e9f7d7a574d
Revises: 
Create Date: 2026-07-29 18:28:06.562054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9f7d7a574d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_audit',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_key', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_audit_action'), 'graph_audit', ['action'], unique=False)
    op.create_index(op.f('ix_graph_audit_actor_id'), 'graph_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_graph_audit_entity_key'), 'graph_audit', ['entity_key'], unique=False)
    op.create_index(op.f('ix_graph_audit_entity_type'), 'graph_audit', ['entity_type'], unique=False)
    op.create_index(op.f('ix_graph_audit_occurred_at'), 'graph_audit', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_graph_audit_outcome'), 'graph_audit', ['outcome'], unique=False)
    op.create_table('graph_change_history',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('node_key', sa.String(length=255), nullable=True),
    sa.Column('relationship_key', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('sync_job_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_change_history_action'), 'graph_change_history', ['action'], unique=False)
    op.create_index(op.f('ix_graph_change_history_actor_id'), 'graph_change_history', ['actor_id'], unique=False)
    op.create_index(op.f('ix_graph_change_history_entity_type'), 'graph_change_history', ['entity_type'], unique=False)
    op.create_index(op.f('ix_graph_change_history_node_key'), 'graph_change_history', ['node_key'], unique=False)
    op.create_index(op.f('ix_graph_change_history_occurred_at'), 'graph_change_history', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_graph_change_history_relationship_key'), 'graph_change_history', ['relationship_key'], unique=False)
    op.create_index(op.f('ix_graph_change_history_sync_job_id'), 'graph_change_history', ['sync_job_id'], unique=False)
    op.create_table('graph_export_jobs',
    sa.Column('export_format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.LargeBinary(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_export_jobs_export_format'), 'graph_export_jobs', ['export_format'], unique=False)
    op.create_index(op.f('ix_graph_export_jobs_status'), 'graph_export_jobs', ['status'], unique=False)
    op.create_table('graph_import_jobs',
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('import_format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('nodes_imported', sa.Integer(), nullable=False),
    sa.Column('relationships_imported', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('rejections', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_import_jobs_import_format'), 'graph_import_jobs', ['import_format'], unique=False)
    op.create_index(op.f('ix_graph_import_jobs_status'), 'graph_import_jobs', ['status'], unique=False)
    op.create_table('graph_metadata',
    sa.Column('node_key', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('twin_type', sa.String(length=24), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=16), nullable=False),
    sa.Column('health_status', sa.String(length=16), nullable=True),
    sa.Column('criticality', sa.Float(), nullable=False),
    sa.Column('owner_team', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'node_key', name='uq_graph_metadata_node')
    )
    op.create_index(op.f('ix_graph_metadata_criticality'), 'graph_metadata', ['criticality'], unique=False)
    op.create_index(op.f('ix_graph_metadata_health_status'), 'graph_metadata', ['health_status'], unique=False)
    op.create_index(op.f('ix_graph_metadata_lifecycle_state'), 'graph_metadata', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_graph_metadata_node_key'), 'graph_metadata', ['node_key'], unique=False)
    op.create_index(op.f('ix_graph_metadata_node_type'), 'graph_metadata', ['node_type'], unique=False)
    op.create_index(op.f('ix_graph_metadata_owner_team'), 'graph_metadata', ['owner_team'], unique=False)
    op.create_index(op.f('ix_graph_metadata_twin_type'), 'graph_metadata', ['twin_type'], unique=False)
    op.create_table('graph_queries',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('cypher', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('saved_query_id', sa.Uuid(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.Uuid(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_queries_executed_at'), 'graph_queries', ['executed_at'], unique=False)
    op.create_index(op.f('ix_graph_queries_executed_by'), 'graph_queries', ['executed_by'], unique=False)
    op.create_index(op.f('ix_graph_queries_kind'), 'graph_queries', ['kind'], unique=False)
    op.create_index(op.f('ix_graph_queries_saved_query_id'), 'graph_queries', ['saved_query_id'], unique=False)
    op.create_index(op.f('ix_graph_queries_succeeded'), 'graph_queries', ['succeeded'], unique=False)
    op.create_table('graph_reports',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=True),
    sa.Column('root_key', sa.String(length=255), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_reports_algorithm'), 'graph_reports', ['algorithm'], unique=False)
    op.create_index(op.f('ix_graph_reports_generated_at'), 'graph_reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_graph_reports_generated_by'), 'graph_reports', ['generated_by'], unique=False)
    op.create_index(op.f('ix_graph_reports_kind'), 'graph_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_graph_reports_root_key'), 'graph_reports', ['root_key'], unique=False)
    op.create_index(op.f('ix_graph_reports_title'), 'graph_reports', ['title'], unique=False)
    op.create_table('graph_saved_queries',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('cypher', sa.Text(), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=False),
    sa.Column('default_parameters', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_graph_saved_query_slug')
    )
    op.create_index(op.f('ix_graph_saved_queries_is_system'), 'graph_saved_queries', ['is_system'], unique=False)
    op.create_index(op.f('ix_graph_saved_queries_kind'), 'graph_saved_queries', ['kind'], unique=False)
    op.create_index(op.f('ix_graph_saved_queries_name'), 'graph_saved_queries', ['name'], unique=False)
    op.create_index(op.f('ix_graph_saved_queries_owner_id'), 'graph_saved_queries', ['owner_id'], unique=False)
    op.create_index(op.f('ix_graph_saved_queries_slug'), 'graph_saved_queries', ['slug'], unique=False)
    op.create_table('graph_snapshots',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('snapshot_format', sa.String(length=16), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.LargeBinary(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_snapshots_captured_at'), 'graph_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_graph_snapshots_expires_at'), 'graph_snapshots', ['expires_at'], unique=False)
    op.create_index(op.f('ix_graph_snapshots_label'), 'graph_snapshots', ['label'], unique=False)
    op.create_index(op.f('ix_graph_snapshots_status'), 'graph_snapshots', ['status'], unique=False)
    op.create_table('graph_statistics',
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('node_type_counts', sa.JSON(), nullable=False),
    sa.Column('relationship_type_counts', sa.JSON(), nullable=False),
    sa.Column('orphan_count', sa.Integer(), nullable=False),
    sa.Column('average_degree', sa.Float(), nullable=False),
    sa.Column('max_degree', sa.Integer(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('connected_components', sa.Integer(), nullable=False),
    sa.Column('critical_assets', sa.JSON(), nullable=False),
    sa.Column('twin_counts', sa.JSON(), nullable=False),
    sa.Column('sync_health', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_statistics_computed_at'), 'graph_statistics', ['computed_at'], unique=False)
    op.create_table('graph_sync_jobs',
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('conflict_resolution', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('cursor', sa.String(length=255), nullable=True),
    sa.Column('nodes_created', sa.Integer(), nullable=False),
    sa.Column('nodes_updated', sa.Integer(), nullable=False),
    sa.Column('nodes_deleted', sa.Integer(), nullable=False),
    sa.Column('relationships_created', sa.Integer(), nullable=False),
    sa.Column('relationships_deleted', sa.Integer(), nullable=False),
    sa.Column('conflicts_detected', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_sync_jobs_mode'), 'graph_sync_jobs', ['mode'], unique=False)
    op.create_index(op.f('ix_graph_sync_jobs_source'), 'graph_sync_jobs', ['source'], unique=False)
    op.create_index(op.f('ix_graph_sync_jobs_started_at'), 'graph_sync_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_graph_sync_jobs_status'), 'graph_sync_jobs', ['status'], unique=False)
    op.create_table('graph_versions',
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('node_type_counts', sa.JSON(), nullable=False),
    sa.Column('relationship_type_counts', sa.JSON(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sequence', name='uq_graph_version_sequence')
    )
    op.create_index(op.f('ix_graph_versions_captured_at'), 'graph_versions', ['captured_at'], unique=False)
    op.create_index(op.f('ix_graph_versions_captured_by'), 'graph_versions', ['captured_by'], unique=False)
    op.create_index(op.f('ix_graph_versions_sequence'), 'graph_versions', ['sequence'], unique=False)
    op.create_index(op.f('ix_graph_versions_snapshot_id'), 'graph_versions', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_versions_snapshot_id'), table_name='graph_versions')
    op.drop_index(op.f('ix_graph_versions_sequence'), table_name='graph_versions')
    op.drop_index(op.f('ix_graph_versions_captured_by'), table_name='graph_versions')
    op.drop_index(op.f('ix_graph_versions_captured_at'), table_name='graph_versions')
    op.drop_table('graph_versions')
    op.drop_index(op.f('ix_graph_sync_jobs_status'), table_name='graph_sync_jobs')
    op.drop_index(op.f('ix_graph_sync_jobs_started_at'), table_name='graph_sync_jobs')
    op.drop_index(op.f('ix_graph_sync_jobs_source'), table_name='graph_sync_jobs')
    op.drop_index(op.f('ix_graph_sync_jobs_mode'), table_name='graph_sync_jobs')
    op.drop_table('graph_sync_jobs')
    op.drop_index(op.f('ix_graph_statistics_computed_at'), table_name='graph_statistics')
    op.drop_table('graph_statistics')
    op.drop_index(op.f('ix_graph_snapshots_status'), table_name='graph_snapshots')
    op.drop_index(op.f('ix_graph_snapshots_label'), table_name='graph_snapshots')
    op.drop_index(op.f('ix_graph_snapshots_expires_at'), table_name='graph_snapshots')
    op.drop_index(op.f('ix_graph_snapshots_captured_at'), table_name='graph_snapshots')
    op.drop_table('graph_snapshots')
    op.drop_index(op.f('ix_graph_saved_queries_slug'), table_name='graph_saved_queries')
    op.drop_index(op.f('ix_graph_saved_queries_owner_id'), table_name='graph_saved_queries')
    op.drop_index(op.f('ix_graph_saved_queries_name'), table_name='graph_saved_queries')
    op.drop_index(op.f('ix_graph_saved_queries_kind'), table_name='graph_saved_queries')
    op.drop_index(op.f('ix_graph_saved_queries_is_system'), table_name='graph_saved_queries')
    op.drop_table('graph_saved_queries')
    op.drop_index(op.f('ix_graph_reports_title'), table_name='graph_reports')
    op.drop_index(op.f('ix_graph_reports_root_key'), table_name='graph_reports')
    op.drop_index(op.f('ix_graph_reports_kind'), table_name='graph_reports')
    op.drop_index(op.f('ix_graph_reports_generated_by'), table_name='graph_reports')
    op.drop_index(op.f('ix_graph_reports_generated_at'), table_name='graph_reports')
    op.drop_index(op.f('ix_graph_reports_algorithm'), table_name='graph_reports')
    op.drop_table('graph_reports')
    op.drop_index(op.f('ix_graph_queries_succeeded'), table_name='graph_queries')
    op.drop_index(op.f('ix_graph_queries_saved_query_id'), table_name='graph_queries')
    op.drop_index(op.f('ix_graph_queries_kind'), table_name='graph_queries')
    op.drop_index(op.f('ix_graph_queries_executed_by'), table_name='graph_queries')
    op.drop_index(op.f('ix_graph_queries_executed_at'), table_name='graph_queries')
    op.drop_table('graph_queries')
    op.drop_index(op.f('ix_graph_metadata_twin_type'), table_name='graph_metadata')
    op.drop_index(op.f('ix_graph_metadata_owner_team'), table_name='graph_metadata')
    op.drop_index(op.f('ix_graph_metadata_node_type'), table_name='graph_metadata')
    op.drop_index(op.f('ix_graph_metadata_node_key'), table_name='graph_metadata')
    op.drop_index(op.f('ix_graph_metadata_lifecycle_state'), table_name='graph_metadata')
    op.drop_index(op.f('ix_graph_metadata_health_status'), table_name='graph_metadata')
    op.drop_index(op.f('ix_graph_metadata_criticality'), table_name='graph_metadata')
    op.drop_table('graph_metadata')
    op.drop_index(op.f('ix_graph_import_jobs_status'), table_name='graph_import_jobs')
    op.drop_index(op.f('ix_graph_import_jobs_import_format'), table_name='graph_import_jobs')
    op.drop_table('graph_import_jobs')
    op.drop_index(op.f('ix_graph_export_jobs_status'), table_name='graph_export_jobs')
    op.drop_index(op.f('ix_graph_export_jobs_export_format'), table_name='graph_export_jobs')
    op.drop_table('graph_export_jobs')
    op.drop_index(op.f('ix_graph_change_history_sync_job_id'), table_name='graph_change_history')
    op.drop_index(op.f('ix_graph_change_history_relationship_key'), table_name='graph_change_history')
    op.drop_index(op.f('ix_graph_change_history_occurred_at'), table_name='graph_change_history')
    op.drop_index(op.f('ix_graph_change_history_node_key'), table_name='graph_change_history')
    op.drop_index(op.f('ix_graph_change_history_entity_type'), table_name='graph_change_history')
    op.drop_index(op.f('ix_graph_change_history_actor_id'), table_name='graph_change_history')
    op.drop_index(op.f('ix_graph_change_history_action'), table_name='graph_change_history')
    op.drop_table('graph_change_history')
    op.drop_index(op.f('ix_graph_audit_outcome'), table_name='graph_audit')
    op.drop_index(op.f('ix_graph_audit_occurred_at'), table_name='graph_audit')
    op.drop_index(op.f('ix_graph_audit_entity_type'), table_name='graph_audit')
    op.drop_index(op.f('ix_graph_audit_entity_key'), table_name='graph_audit')
    op.drop_index(op.f('ix_graph_audit_actor_id'), table_name='graph_audit')
    op.drop_index(op.f('ix_graph_audit_action'), table_name='graph_audit')
    op.drop_table('graph_audit')
    # ### end Alembic commands ###
