"""scheduler service schema

Revision ID: b1c458602dae
Revises:
Create Date: 2026-08-04 19:43:47.127917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1c458602dae"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holiday_calendars",
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("scope_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_holiday_calendars_holiday_date"),
        "holiday_calendars",
        ["holiday_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_holiday_calendars_scope"), "holiday_calendars", ["scope"], unique=False
    )
    op.create_index(
        "ix_holiday_date", "holiday_calendars", ["organization_id", "holiday_date"], unique=False
    )
    op.create_index(
        "ix_holiday_org_scope", "holiday_calendars", ["organization_id", "scope"], unique=False
    )
    op.create_table(
        "job_priorities",
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("escalate_after_minutes", sa.Integer(), nullable=True),
        sa.Column("escalate_to", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "priority", name="uq_job_priority_policy_band"),
    )
    op.create_index(
        op.f("ix_job_priorities_priority"), "job_priorities", ["priority"], unique=False
    )
    op.create_table(
        "maintenance_windows",
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("scope_id", sa.String(length=255), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("recurrence", sa.String(length=32), nullable=False),
        sa.Column("recurrence_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("allow_critical_override", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_maintenance_window_org_scope",
        "maintenance_windows",
        ["organization_id", "scope"],
        unique=False,
    )
    op.create_index(
        "ix_maintenance_window_starts",
        "maintenance_windows",
        ["organization_id", "starts_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_windows_scope"), "maintenance_windows", ["scope"], unique=False
    )
    op.create_index(
        op.f("ix_maintenance_windows_starts_at"), "maintenance_windows", ["starts_at"], unique=False
    )
    op.create_table(
        "scheduled_jobs",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("job_metadata", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("timeout_seconds", sa.Float(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scheduled_job_org_priority",
        "scheduled_jobs",
        ["organization_id", "priority"],
        unique=False,
    )
    op.create_index(
        "ix_scheduled_job_org_status", "scheduled_jobs", ["organization_id", "status"], unique=False
    )
    op.create_index(
        "ix_scheduled_job_org_type", "scheduled_jobs", ["organization_id", "job_type"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_jobs_job_type"), "scheduled_jobs", ["job_type"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_jobs_next_run_at"), "scheduled_jobs", ["next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_jobs_priority"), "scheduled_jobs", ["priority"], unique=False
    )
    op.create_index(op.f("ix_scheduled_jobs_status"), "scheduled_jobs", ["status"], unique=False)
    op.create_table(
        "scheduler_audit",
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("entity_reference", sa.String(length=255), nullable=True),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scheduler_audit_action"), "scheduler_audit", ["action"], unique=False)
    op.create_index(
        op.f("ix_scheduler_audit_entity_id"), "scheduler_audit", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduler_audit_occurred_at"), "scheduler_audit", ["occurred_at"], unique=False
    )
    op.create_table(
        "scheduler_reports",
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("report_format", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("generated_by", sa.String(length=255), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scheduler_reports_kind"), "scheduler_reports", ["kind"], unique=False)
    op.create_table(
        "scheduler_statistics",
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("jobs_scheduled", sa.Integer(), nullable=False),
        sa.Column("jobs_completed", sa.Integer(), nullable=False),
        sa.Column("jobs_failed", sa.Integer(), nullable=False),
        sa.Column("jobs_cancelled", sa.Integer(), nullable=False),
        sa.Column("retry_rate", sa.Float(), nullable=False),
        sa.Column("avg_queue_length", sa.Float(), nullable=False),
        sa.Column("avg_execution_time_seconds", sa.Float(), nullable=True),
        sa.Column("average_delay_seconds", sa.Float(), nullable=True),
        sa.Column("success_rate", sa.Float(), nullable=False),
        sa.Column("scheduler_availability", sa.Float(), nullable=True),
        sa.Column("by_job_type", sa.JSON(), nullable=False),
        sa.Column("by_priority", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "window_start", name="uq_scheduler_statistic_window"
        ),
    )
    op.create_index(
        op.f("ix_scheduler_statistics_window_start"),
        "scheduler_statistics",
        ["window_start"],
        unique=False,
    )
    op.create_table(
        "job_dependencies",
        sa.Column("parent_job_id", sa.Uuid(), nullable=False),
        sa.Column("child_job_id", sa.Uuid(), nullable=False),
        sa.Column("dependency_type", sa.String(length=32), nullable=False),
        sa.Column("condition", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["child_job_id"], ["scheduled_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_job_id"], ["scheduled_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "parent_job_id", "child_job_id", name="uq_job_dependency_edge"
        ),
    )
    op.create_index(
        op.f("ix_job_dependencies_child_job_id"), "job_dependencies", ["child_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_dependencies_parent_job_id"),
        "job_dependencies",
        ["parent_job_id"],
        unique=False,
    )
    op.create_index(
        "ix_job_dependency_child",
        "job_dependencies",
        ["organization_id", "child_job_id"],
        unique=False,
    )
    op.create_index(
        "ix_job_dependency_parent",
        "job_dependencies",
        ["organization_id", "parent_job_id"],
        unique=False,
    )
    op.create_table(
        "job_executions",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("trigger_source", sa.String(length=64), nullable=False),
        sa.Column("priority_snapshot", sa.String(length=32), nullable=False),
        sa.Column("payload_snapshot", sa.JSON(), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("worker_id", sa.String(length=128), nullable=True),
        sa.Column("node_id", sa.String(length=128), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("retries_used", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("execution_metadata", sa.JSON(), nullable=False),
        sa.Column("artifacts", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["scheduled_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_execution_job", "job_executions", ["organization_id", "job_id"], unique=False
    )
    op.create_index(
        "ix_job_execution_org_status", "job_executions", ["organization_id", "status"], unique=False
    )
    op.create_index(
        "ix_job_execution_queued", "job_executions", ["organization_id", "queued_at"], unique=False
    )
    op.create_index(op.f("ix_job_executions_job_id"), "job_executions", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_job_executions_queued_at"), "job_executions", ["queued_at"], unique=False
    )
    op.create_index(op.f("ix_job_executions_status"), "job_executions", ["status"], unique=False)
    op.create_table(
        "job_history",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["scheduled_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_history_job", "job_history", ["organization_id", "job_id"], unique=False
    )
    op.create_index(op.f("ix_job_history_job_id"), "job_history", ["job_id"], unique=False)
    op.create_table(
        "job_retry_policies",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("retry_type", sa.String(length=32), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("base_delay_seconds", sa.Float(), nullable=False),
        sa.Column("max_delay_seconds", sa.Float(), nullable=False),
        sa.Column("retry_conditions", sa.JSON(), nullable=False),
        sa.Column("dead_letter_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["scheduled_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "job_id", name="uq_job_retry_policy_job"),
    )
    op.create_index(
        op.f("ix_job_retry_policies_job_id"), "job_retry_policies", ["job_id"], unique=False
    )
    op.create_table(
        "job_schedules",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_paused", sa.Boolean(), nullable=False),
        sa.Column("pause_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["scheduled_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "job_id", name="uq_job_schedule_job"),
    )
    op.create_index(
        "ix_job_schedule_next_run",
        "job_schedules",
        ["organization_id", "next_run_at"],
        unique=False,
    )
    op.create_index(op.f("ix_job_schedules_job_id"), "job_schedules", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_job_schedules_next_run_at"), "job_schedules", ["next_run_at"], unique=False
    )
    op.create_table(
        "job_triggers",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cron_expression", sa.String(length=128), nullable=True),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("interval_seconds", sa.Float(), nullable=True),
        sa.Column("calendar_rule", sa.String(length=32), nullable=True),
        sa.Column("calendar_config", sa.JSON(), nullable=False),
        sa.Column("event_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["scheduled_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_trigger_job", "job_triggers", ["organization_id", "job_id"], unique=False
    )
    op.create_index(op.f("ix_job_triggers_job_id"), "job_triggers", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_job_triggers_trigger_type"), "job_triggers", ["trigger_type"], unique=False
    )
    op.create_table(
        "job_execution_logs",
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["execution_id"], ["job_executions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_execution_log_execution",
        "job_execution_logs",
        ["organization_id", "execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_execution_logs_execution_id"),
        "job_execution_logs",
        ["execution_id"],
        unique=False,
    )
    op.create_table(
        "job_failures",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("failure_reason", sa.String(length=512), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("is_terminal", sa.Boolean(), nullable=False),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retried", sa.Boolean(), nullable=False),
        sa.Column("recovery_action", sa.String(length=32), nullable=True),
        sa.Column("recovered", sa.Boolean(), nullable=False),
        sa.Column("recovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recovered_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["execution_id"], ["job_executions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["scheduled_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_failure_execution",
        "job_failures",
        ["organization_id", "execution_id"],
        unique=False,
    )
    op.create_index(
        "ix_job_failure_job", "job_failures", ["organization_id", "job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_failures_execution_id"), "job_failures", ["execution_id"], unique=False
    )
    op.create_index(op.f("ix_job_failures_job_id"), "job_failures", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_failures_job_id"), table_name="job_failures")
    op.drop_index(op.f("ix_job_failures_execution_id"), table_name="job_failures")
    op.drop_index("ix_job_failure_job", table_name="job_failures")
    op.drop_index("ix_job_failure_execution", table_name="job_failures")
    op.drop_table("job_failures")
    op.drop_index(op.f("ix_job_execution_logs_execution_id"), table_name="job_execution_logs")
    op.drop_index("ix_job_execution_log_execution", table_name="job_execution_logs")
    op.drop_table("job_execution_logs")
    op.drop_index(op.f("ix_job_triggers_trigger_type"), table_name="job_triggers")
    op.drop_index(op.f("ix_job_triggers_job_id"), table_name="job_triggers")
    op.drop_index("ix_job_trigger_job", table_name="job_triggers")
    op.drop_table("job_triggers")
    op.drop_index(op.f("ix_job_schedules_next_run_at"), table_name="job_schedules")
    op.drop_index(op.f("ix_job_schedules_job_id"), table_name="job_schedules")
    op.drop_index("ix_job_schedule_next_run", table_name="job_schedules")
    op.drop_table("job_schedules")
    op.drop_index(op.f("ix_job_retry_policies_job_id"), table_name="job_retry_policies")
    op.drop_table("job_retry_policies")
    op.drop_index(op.f("ix_job_history_job_id"), table_name="job_history")
    op.drop_index("ix_job_history_job", table_name="job_history")
    op.drop_table("job_history")
    op.drop_index(op.f("ix_job_executions_status"), table_name="job_executions")
    op.drop_index(op.f("ix_job_executions_queued_at"), table_name="job_executions")
    op.drop_index(op.f("ix_job_executions_job_id"), table_name="job_executions")
    op.drop_index("ix_job_execution_queued", table_name="job_executions")
    op.drop_index("ix_job_execution_org_status", table_name="job_executions")
    op.drop_index("ix_job_execution_job", table_name="job_executions")
    op.drop_table("job_executions")
    op.drop_index("ix_job_dependency_parent", table_name="job_dependencies")
    op.drop_index("ix_job_dependency_child", table_name="job_dependencies")
    op.drop_index(op.f("ix_job_dependencies_parent_job_id"), table_name="job_dependencies")
    op.drop_index(op.f("ix_job_dependencies_child_job_id"), table_name="job_dependencies")
    op.drop_table("job_dependencies")
    op.drop_index(op.f("ix_scheduler_statistics_window_start"), table_name="scheduler_statistics")
    op.drop_table("scheduler_statistics")
    op.drop_index(op.f("ix_scheduler_reports_kind"), table_name="scheduler_reports")
    op.drop_table("scheduler_reports")
    op.drop_index(op.f("ix_scheduler_audit_occurred_at"), table_name="scheduler_audit")
    op.drop_index(op.f("ix_scheduler_audit_entity_id"), table_name="scheduler_audit")
    op.drop_index(op.f("ix_scheduler_audit_action"), table_name="scheduler_audit")
    op.drop_table("scheduler_audit")
    op.drop_index(op.f("ix_scheduled_jobs_status"), table_name="scheduled_jobs")
    op.drop_index(op.f("ix_scheduled_jobs_priority"), table_name="scheduled_jobs")
    op.drop_index(op.f("ix_scheduled_jobs_next_run_at"), table_name="scheduled_jobs")
    op.drop_index(op.f("ix_scheduled_jobs_job_type"), table_name="scheduled_jobs")
    op.drop_index("ix_scheduled_job_org_type", table_name="scheduled_jobs")
    op.drop_index("ix_scheduled_job_org_status", table_name="scheduled_jobs")
    op.drop_index("ix_scheduled_job_org_priority", table_name="scheduled_jobs")
    op.drop_table("scheduled_jobs")
    op.drop_index(op.f("ix_maintenance_windows_starts_at"), table_name="maintenance_windows")
    op.drop_index(op.f("ix_maintenance_windows_scope"), table_name="maintenance_windows")
    op.drop_index("ix_maintenance_window_starts", table_name="maintenance_windows")
    op.drop_index("ix_maintenance_window_org_scope", table_name="maintenance_windows")
    op.drop_table("maintenance_windows")
    op.drop_index(op.f("ix_job_priorities_priority"), table_name="job_priorities")
    op.drop_table("job_priorities")
    op.drop_index("ix_holiday_org_scope", table_name="holiday_calendars")
    op.drop_index("ix_holiday_date", table_name="holiday_calendars")
    op.drop_index(op.f("ix_holiday_calendars_scope"), table_name="holiday_calendars")
    op.drop_index(op.f("ix_holiday_calendars_holiday_date"), table_name="holiday_calendars")
    op.drop_table("holiday_calendars")
    # ### end Alembic commands ###
