"""initial dashboard schema

Revision ID: 6d1566494b08
Revises: 
Create Date: 2026-07-29 00:06:52.900514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1566494b08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_audit',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_audit_action'), 'dashboard_audit', ['action'], unique=False)
    op.create_index(op.f('ix_dashboard_audit_actor_id'), 'dashboard_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_dashboard_audit_entity_id'), 'dashboard_audit', ['entity_id'], unique=False)
    op.create_index(op.f('ix_dashboard_audit_entity_type'), 'dashboard_audit', ['entity_type'], unique=False)
    op.create_index(op.f('ix_dashboard_audit_occurred_at'), 'dashboard_audit', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_dashboard_audit_outcome'), 'dashboard_audit', ['outcome'], unique=False)
    op.create_table('dashboard_statistics',
    sa.Column('total_dashboards', sa.Integer(), nullable=False),
    sa.Column('total_widgets', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('unique_viewers', sa.Integer(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('average_load_ms', sa.Float(), nullable=False),
    sa.Column('widget_failure_rate', sa.Float(), nullable=False),
    sa.Column('most_viewed', sa.JSON(), nullable=False),
    sa.Column('widget_usage', sa.JSON(), nullable=False),
    sa.Column('dashboard_type_usage', sa.JSON(), nullable=False),
    sa.Column('refresh_usage', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_statistics_computed_at'), 'dashboard_statistics', ['computed_at'], unique=False)
    op.create_table('dashboard_templates',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dashboard_type', sa.String(length=24), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_dashboard_template_slug')
    )
    op.create_index(op.f('ix_dashboard_templates_dashboard_type'), 'dashboard_templates', ['dashboard_type'], unique=False)
    op.create_index(op.f('ix_dashboard_templates_is_system'), 'dashboard_templates', ['is_system'], unique=False)
    op.create_index(op.f('ix_dashboard_templates_name'), 'dashboard_templates', ['name'], unique=False)
    op.create_index(op.f('ix_dashboard_templates_slug'), 'dashboard_templates', ['slug'], unique=False)
    op.create_table('dashboard_themes',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('palette', sa.JSON(), nullable=False),
    sa.Column('branding', sa.JSON(), nullable=False),
    sa.Column('accessibility', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_dashboard_theme_slug')
    )
    op.create_index(op.f('ix_dashboard_themes_is_system'), 'dashboard_themes', ['is_system'], unique=False)
    op.create_index(op.f('ix_dashboard_themes_mode'), 'dashboard_themes', ['mode'], unique=False)
    op.create_index(op.f('ix_dashboard_themes_slug'), 'dashboard_themes', ['slug'], unique=False)
    op.create_table('dashboards',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dashboard_type', sa.String(length=24), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('theme_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('default_filters', sa.JSON(), nullable=False),
    sa.Column('refresh_seconds', sa.Integer(), nullable=False),
    sa.Column('layout_revision', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['dashboard_themes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_dashboard_org_slug')
    )
    op.create_index(op.f('ix_dashboards_dashboard_type'), 'dashboards', ['dashboard_type'], unique=False)
    op.create_index(op.f('ix_dashboards_enabled'), 'dashboards', ['enabled'], unique=False)
    op.create_index(op.f('ix_dashboards_name'), 'dashboards', ['name'], unique=False)
    op.create_index(op.f('ix_dashboards_owner_id'), 'dashboards', ['owner_id'], unique=False)
    op.create_index(op.f('ix_dashboards_slug'), 'dashboards', ['slug'], unique=False)
    op.create_index(op.f('ix_dashboards_theme_id'), 'dashboards', ['theme_id'], unique=False)
    op.create_index(op.f('ix_dashboards_visibility'), 'dashboards', ['visibility'], unique=False)
    op.create_table('dashboard_favorites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dashboard_id', name='uq_dashboard_favorite_user')
    )
    op.create_index(op.f('ix_dashboard_favorites_dashboard_id'), 'dashboard_favorites', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_favorites_user_id'), 'dashboard_favorites', ['user_id'], unique=False)
    op.create_table('dashboard_filters',
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('clauses', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'user_id', 'name', name='uq_dashboard_filter_name')
    )
    op.create_index(op.f('ix_dashboard_filters_dashboard_id'), 'dashboard_filters', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_filters_user_id'), 'dashboard_filters', ['user_id'], unique=False)
    op.create_table('dashboard_history',
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('layout_revision', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_history_actor_id'), 'dashboard_history', ['actor_id'], unique=False)
    op.create_index(op.f('ix_dashboard_history_dashboard_id'), 'dashboard_history', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_history_event'), 'dashboard_history', ['event'], unique=False)
    op.create_index(op.f('ix_dashboard_history_occurred_at'), 'dashboard_history', ['occurred_at'], unique=False)
    op.create_table('dashboard_layouts',
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('breakpoint', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=False),
    sa.Column('row_height', sa.Integer(), nullable=False),
    sa.Column('placements', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_by_user', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'breakpoint', 'revision', name='uq_layout_dashboard_bp_revision')
    )
    op.create_index(op.f('ix_dashboard_layouts_breakpoint'), 'dashboard_layouts', ['breakpoint'], unique=False)
    op.create_index(op.f('ix_dashboard_layouts_created_by_user'), 'dashboard_layouts', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_dashboard_layouts_dashboard_id'), 'dashboard_layouts', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_layouts_is_current'), 'dashboard_layouts', ['is_current'], unique=False)
    op.create_index(op.f('ix_dashboard_layouts_revision'), 'dashboard_layouts', ['revision'], unique=False)
    op.create_table('dashboard_permissions',
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'role', name='uq_dashboard_permission_role')
    )
    op.create_index(op.f('ix_dashboard_permissions_dashboard_id'), 'dashboard_permissions', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_permissions_enabled'), 'dashboard_permissions', ['enabled'], unique=False)
    op.create_index(op.f('ix_dashboard_permissions_permission'), 'dashboard_permissions', ['permission'], unique=False)
    op.create_index(op.f('ix_dashboard_permissions_role'), 'dashboard_permissions', ['role'], unique=False)
    op.create_table('dashboard_shares',
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('shared_with_user_id', sa.Uuid(), nullable=True),
    sa.Column('shared_with_role', sa.String(length=64), nullable=True),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('shared_by', sa.Uuid(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_shares_dashboard_id'), 'dashboard_shares', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_expires_at'), 'dashboard_shares', ['expires_at'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_is_revoked'), 'dashboard_shares', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_permission'), 'dashboard_shares', ['permission'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_share_token'), 'dashboard_shares', ['share_token'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_shared_by'), 'dashboard_shares', ['shared_by'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_shared_with_role'), 'dashboard_shares', ['shared_with_role'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_shared_with_user_id'), 'dashboard_shares', ['shared_with_user_id'], unique=False)
    op.create_table('dashboard_views',
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('load_ms', sa.Float(), nullable=True),
    sa.Column('widget_count', sa.Integer(), nullable=False),
    sa.Column('failed_widget_count', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_views_dashboard_id'), 'dashboard_views', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_views_user_id'), 'dashboard_views', ['user_id'], unique=False)
    op.create_index(op.f('ix_dashboard_views_viewed_at'), 'dashboard_views', ['viewed_at'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('widget_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('widget_type', sa.String(length=24), nullable=False),
    sa.Column('data_source', sa.String(length=24), nullable=False),
    sa.Column('query', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('refresh_mode', sa.String(length=16), nullable=False),
    sa.Column('refresh_seconds', sa.Integer(), nullable=False),
    sa.Column('cache_seconds', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'widget_key', name='uq_dashboard_widget_key')
    )
    op.create_index(op.f('ix_dashboard_widgets_dashboard_id'), 'dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_data_source'), 'dashboard_widgets', ['data_source'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_enabled'), 'dashboard_widgets', ['enabled'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_widget_key'), 'dashboard_widgets', ['widget_key'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_widget_type'), 'dashboard_widgets', ['widget_type'], unique=False)
    op.create_table('dashboard_widget_settings',
    sa.Column('widget_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('collapsed', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('refresh_seconds_override', sa.Integer(), nullable=True),
    sa.Column('options_override', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['dashboard_widgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('widget_id', 'user_id', name='uq_widget_setting_widget_user')
    )
    op.create_index(op.f('ix_dashboard_widget_settings_user_id'), 'dashboard_widget_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_dashboard_widget_settings_widget_id'), 'dashboard_widget_settings', ['widget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_widget_settings_widget_id'), table_name='dashboard_widget_settings')
    op.drop_index(op.f('ix_dashboard_widget_settings_user_id'), table_name='dashboard_widget_settings')
    op.drop_table('dashboard_widget_settings')
    op.drop_index(op.f('ix_dashboard_widgets_widget_type'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_widget_key'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_enabled'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_data_source'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_dashboard_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_views_viewed_at'), table_name='dashboard_views')
    op.drop_index(op.f('ix_dashboard_views_user_id'), table_name='dashboard_views')
    op.drop_index(op.f('ix_dashboard_views_dashboard_id'), table_name='dashboard_views')
    op.drop_table('dashboard_views')
    op.drop_index(op.f('ix_dashboard_shares_shared_with_user_id'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_shared_with_role'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_shared_by'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_share_token'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_permission'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_is_revoked'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_expires_at'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_dashboard_id'), table_name='dashboard_shares')
    op.drop_table('dashboard_shares')
    op.drop_index(op.f('ix_dashboard_permissions_role'), table_name='dashboard_permissions')
    op.drop_index(op.f('ix_dashboard_permissions_permission'), table_name='dashboard_permissions')
    op.drop_index(op.f('ix_dashboard_permissions_enabled'), table_name='dashboard_permissions')
    op.drop_index(op.f('ix_dashboard_permissions_dashboard_id'), table_name='dashboard_permissions')
    op.drop_table('dashboard_permissions')
    op.drop_index(op.f('ix_dashboard_layouts_revision'), table_name='dashboard_layouts')
    op.drop_index(op.f('ix_dashboard_layouts_is_current'), table_name='dashboard_layouts')
    op.drop_index(op.f('ix_dashboard_layouts_dashboard_id'), table_name='dashboard_layouts')
    op.drop_index(op.f('ix_dashboard_layouts_created_by_user'), table_name='dashboard_layouts')
    op.drop_index(op.f('ix_dashboard_layouts_breakpoint'), table_name='dashboard_layouts')
    op.drop_table('dashboard_layouts')
    op.drop_index(op.f('ix_dashboard_history_occurred_at'), table_name='dashboard_history')
    op.drop_index(op.f('ix_dashboard_history_event'), table_name='dashboard_history')
    op.drop_index(op.f('ix_dashboard_history_dashboard_id'), table_name='dashboard_history')
    op.drop_index(op.f('ix_dashboard_history_actor_id'), table_name='dashboard_history')
    op.drop_table('dashboard_history')
    op.drop_index(op.f('ix_dashboard_filters_user_id'), table_name='dashboard_filters')
    op.drop_index(op.f('ix_dashboard_filters_dashboard_id'), table_name='dashboard_filters')
    op.drop_table('dashboard_filters')
    op.drop_index(op.f('ix_dashboard_favorites_user_id'), table_name='dashboard_favorites')
    op.drop_index(op.f('ix_dashboard_favorites_dashboard_id'), table_name='dashboard_favorites')
    op.drop_table('dashboard_favorites')
    op.drop_index(op.f('ix_dashboards_visibility'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_theme_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_slug'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_owner_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_name'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_enabled'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_dashboard_type'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_dashboard_themes_slug'), table_name='dashboard_themes')
    op.drop_index(op.f('ix_dashboard_themes_mode'), table_name='dashboard_themes')
    op.drop_index(op.f('ix_dashboard_themes_is_system'), table_name='dashboard_themes')
    op.drop_table('dashboard_themes')
    op.drop_index(op.f('ix_dashboard_templates_slug'), table_name='dashboard_templates')
    op.drop_index(op.f('ix_dashboard_templates_name'), table_name='dashboard_templates')
    op.drop_index(op.f('ix_dashboard_templates_is_system'), table_name='dashboard_templates')
    op.drop_index(op.f('ix_dashboard_templates_dashboard_type'), table_name='dashboard_templates')
    op.drop_table('dashboard_templates')
    op.drop_index(op.f('ix_dashboard_statistics_computed_at'), table_name='dashboard_statistics')
    op.drop_table('dashboard_statistics')
    op.drop_index(op.f('ix_dashboard_audit_outcome'), table_name='dashboard_audit')
    op.drop_index(op.f('ix_dashboard_audit_occurred_at'), table_name='dashboard_audit')
    op.drop_index(op.f('ix_dashboard_audit_entity_type'), table_name='dashboard_audit')
    op.drop_index(op.f('ix_dashboard_audit_entity_id'), table_name='dashboard_audit')
    op.drop_index(op.f('ix_dashboard_audit_actor_id'), table_name='dashboard_audit')
    op.drop_index(op.f('ix_dashboard_audit_action'), table_name='dashboard_audit')
    op.drop_table('dashboard_audit')
    # ### end Alembic commands ###
