"""change management service schema

Revision ID: 678760a2f307
Revises: 
Create Date: 2026-08-04 14:01:40.155538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678760a2f307'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_audit',
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_audit_action', 'change_audit', ['organization_id', 'action'], unique=False)
    op.create_index('ix_change_audit_actor', 'change_audit', ['organization_id', 'actor_id'], unique=False)
    op.create_index(op.f('ix_change_audit_actor_id'), 'change_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_change_audit_entity_id'), 'change_audit', ['entity_id'], unique=False)
    op.create_index(op.f('ix_change_audit_entity_type'), 'change_audit', ['entity_type'], unique=False)
    op.create_index(op.f('ix_change_audit_occurred_at'), 'change_audit', ['occurred_at'], unique=False)
    op.create_index('ix_change_audit_org', 'change_audit', ['organization_id', 'occurred_at'], unique=False)
    op.create_table('change_calendar',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('recurrence', sa.String(length=16), nullable=False),
    sa.Column('recurrence_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_org_wide', sa.Boolean(), nullable=False),
    sa.Column('capacity_limit', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_calendar_ends_at'), 'change_calendar', ['ends_at'], unique=False)
    op.create_index(op.f('ix_change_calendar_kind'), 'change_calendar', ['kind'], unique=False)
    op.create_index(op.f('ix_change_calendar_starts_at'), 'change_calendar', ['starts_at'], unique=False)
    op.create_table('change_categories',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_change_category_slug')
    )
    op.create_index(op.f('ix_change_categories_category'), 'change_categories', ['category'], unique=False)
    op.create_index(op.f('ix_change_categories_slug'), 'change_categories', ['slug'], unique=False)
    op.create_table('change_priorities',
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('approval_window_hours', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'priority', name='uq_change_priority')
    )
    op.create_index(op.f('ix_change_priorities_priority'), 'change_priorities', ['priority'], unique=False)
    op.create_table('change_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changes_created', sa.Integer(), nullable=False),
    sa.Column('changes_completed', sa.Integer(), nullable=False),
    sa.Column('changes_rolled_back', sa.Integer(), nullable=False),
    sa.Column('changes_rejected', sa.Integer(), nullable=False),
    sa.Column('changes_cancelled', sa.Integer(), nullable=False),
    sa.Column('emergency_changes', sa.Integer(), nullable=False),
    sa.Column('open_total', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('avg_approval_duration_seconds', sa.Float(), nullable=True),
    sa.Column('avg_implementation_duration_seconds', sa.Float(), nullable=True),
    sa.Column('conflicts_detected', sa.Integer(), nullable=False),
    sa.Column('by_risk_level', sa.JSON(), nullable=False),
    sa.Column('by_category', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_statistic_org', 'change_statistics', ['organization_id', 'window_start'], unique=False)
    op.create_index(op.f('ix_change_statistics_window_start'), 'change_statistics', ['window_start'], unique=False)
    op.create_table('change_status',
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'status', name='uq_change_status_record')
    )
    op.create_index(op.f('ix_change_status_status'), 'change_status', ['status'], unique=False)
    op.create_table('change_types',
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_cab', sa.Boolean(), nullable=True),
    sa.Column('requires_risk_assessment', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'change_type', name='uq_change_type')
    )
    op.create_index(op.f('ix_change_types_change_type'), 'change_types', ['change_type'], unique=False)
    op.create_table('change_requests',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('requester_id', sa.String(length=255), nullable=False),
    sa.Column('business_owner_id', sa.String(length=255), nullable=True),
    sa.Column('technical_owner_id', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('affected_assets', sa.JSON(), nullable=False),
    sa.Column('affected_services', sa.JSON(), nullable=False),
    sa.Column('affected_applications', sa.JSON(), nullable=False),
    sa.Column('implementation_plan', sa.Text(), nullable=True),
    sa.Column('validation_plan', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('cab_required', sa.Boolean(), nullable=False),
    sa.Column('calendar_entry_id', sa.Uuid(), nullable=True),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('problem_id', sa.String(length=64), nullable=True),
    sa.Column('known_error_id', sa.String(length=64), nullable=True),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_duration_seconds', sa.Float(), nullable=True),
    sa.Column('implementation_duration_seconds', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_entry_id'], ['change_calendar.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'reference', name='uq_change_reference')
    )
    op.create_index('ix_change_assignee', 'change_requests', ['organization_id', 'technical_owner_id'], unique=False)
    op.create_index('ix_change_org_created', 'change_requests', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_change_org_priority', 'change_requests', ['organization_id', 'priority'], unique=False)
    op.create_index('ix_change_org_status', 'change_requests', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_change_requests_category'), 'change_requests', ['category'], unique=False)
    op.create_index(op.f('ix_change_requests_change_type'), 'change_requests', ['change_type'], unique=False)
    op.create_index(op.f('ix_change_requests_incident_id'), 'change_requests', ['incident_id'], unique=False)
    op.create_index(op.f('ix_change_requests_priority'), 'change_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_change_requests_risk_level'), 'change_requests', ['risk_level'], unique=False)
    op.create_index(op.f('ix_change_requests_scheduled_start_at'), 'change_requests', ['scheduled_start_at'], unique=False)
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    op.create_table('change_approvals',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('policy', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.String(length=255), nullable=False),
    sa.Column('approver_role', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delegated_to', sa.String(length=255), nullable=True),
    sa.Column('delegated_from', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'change_id', 'level', 'approver_id', name='uq_change_approval_step')
    )
    op.create_index('ix_change_approval_change', 'change_approvals', ['organization_id', 'change_id', 'level'], unique=False)
    op.create_index('ix_change_approval_status', 'change_approvals', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_change_approvals_change_id'), 'change_approvals', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_approvals_expires_at'), 'change_approvals', ['expires_at'], unique=False)
    op.create_index(op.f('ix_change_approvals_status'), 'change_approvals', ['status'], unique=False)
    op.create_table('change_cab',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chair_id', sa.String(length=255), nullable=True),
    sa.Column('is_emergency_cab', sa.Boolean(), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quorum_fraction_required', sa.Float(), nullable=False),
    sa.Column('invited_count', sa.Integer(), nullable=False),
    sa.Column('quorum_met', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_cab_change', 'change_cab', ['organization_id', 'change_id'], unique=False)
    op.create_index(op.f('ix_change_cab_change_id'), 'change_cab', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_cab_status'), 'change_cab', ['status'], unique=False)
    op.create_table('change_conflicts',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('conflicting_change_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conflicting_change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'change_id', 'conflicting_change_id', 'kind', name='uq_change_conflict')
    )
    op.create_index('ix_change_conflict_change', 'change_conflicts', ['organization_id', 'change_id'], unique=False)
    op.create_index('ix_change_conflict_status', 'change_conflicts', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_change_conflicts_change_id'), 'change_conflicts', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_conflicts_conflicting_change_id'), 'change_conflicts', ['conflicting_change_id'], unique=False)
    op.create_index(op.f('ix_change_conflicts_detected_at'), 'change_conflicts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_change_conflicts_kind'), 'change_conflicts', ['kind'], unique=False)
    op.create_index(op.f('ix_change_conflicts_status'), 'change_conflicts', ['status'], unique=False)
    op.create_table('change_implementations',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_implementation_change', 'change_implementations', ['organization_id', 'change_id'], unique=False)
    op.create_index(op.f('ix_change_implementations_change_id'), 'change_implementations', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_implementations_status'), 'change_implementations', ['status'], unique=False)
    op.create_table('change_post_reviews',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('implementation_summary', sa.Text(), nullable=True),
    sa.Column('objectives_achieved', sa.Text(), nullable=True),
    sa.Column('unexpected_issues', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('risk_review', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'change_id', name='uq_change_post_review_change')
    )
    op.create_index(op.f('ix_change_post_reviews_change_id'), 'change_post_reviews', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_post_reviews_status'), 'change_post_reviews', ['status'], unique=False)
    op.create_table('change_relationships',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('related_change_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'change_id', 'related_change_id', 'kind', name='uq_change_relationship')
    )
    op.create_index('ix_change_relationship_change', 'change_relationships', ['organization_id', 'change_id'], unique=False)
    op.create_index('ix_change_relationship_related', 'change_relationships', ['organization_id', 'related_change_id'], unique=False)
    op.create_index(op.f('ix_change_relationships_change_id'), 'change_relationships', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_relationships_kind'), 'change_relationships', ['kind'], unique=False)
    op.create_index(op.f('ix_change_relationships_related_change_id'), 'change_relationships', ['related_change_id'], unique=False)
    op.create_table('change_reports',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_id', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_report_org', 'change_reports', ['organization_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_change_reports_generated_at'), 'change_reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_change_reports_kind'), 'change_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_change_reports_status'), 'change_reports', ['status'], unique=False)
    op.create_table('change_risk_assessments',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('likelihood', sa.String(length=32), nullable=False),
    sa.Column('impact', sa.String(length=32), nullable=False),
    sa.Column('technical_risk', sa.String(length=32), nullable=False),
    sa.Column('business_risk', sa.String(length=32), nullable=False),
    sa.Column('operational_risk', sa.String(length=32), nullable=False),
    sa.Column('security_risk', sa.String(length=32), nullable=False),
    sa.Column('compliance_risk', sa.String(length=32), nullable=False),
    sa.Column('dependency_risk', sa.String(length=32), nullable=False),
    sa.Column('automated_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('manual_override', sa.String(length=32), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('override_by', sa.String(length=255), nullable=True),
    sa.Column('approval_recommendation', sa.Text(), nullable=False),
    sa.Column('assessed_by', sa.String(length=255), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_risk_assessments_assessed_at'), 'change_risk_assessments', ['assessed_at'], unique=False)
    op.create_index(op.f('ix_change_risk_assessments_change_id'), 'change_risk_assessments', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_risk_assessments_risk_level'), 'change_risk_assessments', ['risk_level'], unique=False)
    op.create_index('ix_risk_assessment_change', 'change_risk_assessments', ['organization_id', 'change_id', 'assessed_at'], unique=False)
    op.create_table('change_rollbacks',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('triggered_reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_summary', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_rollback_change', 'change_rollbacks', ['organization_id', 'change_id'], unique=False)
    op.create_index(op.f('ix_change_rollbacks_change_id'), 'change_rollbacks', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_rollbacks_status'), 'change_rollbacks', ['status'], unique=False)
    op.create_table('change_tasks',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('automation_reference', sa.String(length=255), nullable=True),
    sa.Column('workflow_reference', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_task_change', 'change_tasks', ['organization_id', 'change_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_change_tasks_change_id'), 'change_tasks', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_tasks_status'), 'change_tasks', ['status'], unique=False)
    op.create_table('change_validations',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_gate', sa.Boolean(), nullable=False),
    sa.Column('ran_by', sa.String(length=255), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_validation_change', 'change_validations', ['organization_id', 'change_id', 'kind'], unique=False)
    op.create_index(op.f('ix_change_validations_change_id'), 'change_validations', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_validations_kind'), 'change_validations', ['kind'], unique=False)
    op.create_index(op.f('ix_change_validations_status'), 'change_validations', ['status'], unique=False)
    op.create_table('change_cab_votes',
    sa.Column('cab_id', sa.Uuid(), nullable=False),
    sa.Column('voter_id', sa.String(length=255), nullable=False),
    sa.Column('vote', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cab_id'], ['change_cab.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'cab_id', 'voter_id', name='uq_change_cab_vote')
    )
    op.create_index('ix_change_cab_vote_cab', 'change_cab_votes', ['organization_id', 'cab_id'], unique=False)
    op.create_index(op.f('ix_change_cab_votes_cab_id'), 'change_cab_votes', ['cab_id'], unique=False)
    op.create_index(op.f('ix_change_cab_votes_voter_id'), 'change_cab_votes', ['voter_id'], unique=False)
    op.create_table('change_post_review_action_items',
    sa.Column('post_review_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['post_review_id'], ['change_post_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_post_review_action_items_owner_id'), 'change_post_review_action_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_change_post_review_action_items_post_review_id'), 'change_post_review_action_items', ['post_review_id'], unique=False)
    op.create_index(op.f('ix_change_post_review_action_items_status'), 'change_post_review_action_items', ['status'], unique=False)
    op.create_index('ix_pir_action_item_owner', 'change_post_review_action_items', ['organization_id', 'owner_id'], unique=False)
    op.create_index('ix_pir_action_item_review', 'change_post_review_action_items', ['organization_id', 'post_review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pir_action_item_review', table_name='change_post_review_action_items')
    op.drop_index('ix_pir_action_item_owner', table_name='change_post_review_action_items')
    op.drop_index(op.f('ix_change_post_review_action_items_status'), table_name='change_post_review_action_items')
    op.drop_index(op.f('ix_change_post_review_action_items_post_review_id'), table_name='change_post_review_action_items')
    op.drop_index(op.f('ix_change_post_review_action_items_owner_id'), table_name='change_post_review_action_items')
    op.drop_table('change_post_review_action_items')
    op.drop_index(op.f('ix_change_cab_votes_voter_id'), table_name='change_cab_votes')
    op.drop_index(op.f('ix_change_cab_votes_cab_id'), table_name='change_cab_votes')
    op.drop_index('ix_change_cab_vote_cab', table_name='change_cab_votes')
    op.drop_table('change_cab_votes')
    op.drop_index(op.f('ix_change_validations_status'), table_name='change_validations')
    op.drop_index(op.f('ix_change_validations_kind'), table_name='change_validations')
    op.drop_index(op.f('ix_change_validations_change_id'), table_name='change_validations')
    op.drop_index('ix_change_validation_change', table_name='change_validations')
    op.drop_table('change_validations')
    op.drop_index(op.f('ix_change_tasks_status'), table_name='change_tasks')
    op.drop_index(op.f('ix_change_tasks_change_id'), table_name='change_tasks')
    op.drop_index('ix_change_task_change', table_name='change_tasks')
    op.drop_table('change_tasks')
    op.drop_index(op.f('ix_change_rollbacks_status'), table_name='change_rollbacks')
    op.drop_index(op.f('ix_change_rollbacks_change_id'), table_name='change_rollbacks')
    op.drop_index('ix_change_rollback_change', table_name='change_rollbacks')
    op.drop_table('change_rollbacks')
    op.drop_index('ix_risk_assessment_change', table_name='change_risk_assessments')
    op.drop_index(op.f('ix_change_risk_assessments_risk_level'), table_name='change_risk_assessments')
    op.drop_index(op.f('ix_change_risk_assessments_change_id'), table_name='change_risk_assessments')
    op.drop_index(op.f('ix_change_risk_assessments_assessed_at'), table_name='change_risk_assessments')
    op.drop_table('change_risk_assessments')
    op.drop_index(op.f('ix_change_reports_status'), table_name='change_reports')
    op.drop_index(op.f('ix_change_reports_kind'), table_name='change_reports')
    op.drop_index(op.f('ix_change_reports_generated_at'), table_name='change_reports')
    op.drop_index('ix_change_report_org', table_name='change_reports')
    op.drop_table('change_reports')
    op.drop_index(op.f('ix_change_relationships_related_change_id'), table_name='change_relationships')
    op.drop_index(op.f('ix_change_relationships_kind'), table_name='change_relationships')
    op.drop_index(op.f('ix_change_relationships_change_id'), table_name='change_relationships')
    op.drop_index('ix_change_relationship_related', table_name='change_relationships')
    op.drop_index('ix_change_relationship_change', table_name='change_relationships')
    op.drop_table('change_relationships')
    op.drop_index(op.f('ix_change_post_reviews_status'), table_name='change_post_reviews')
    op.drop_index(op.f('ix_change_post_reviews_change_id'), table_name='change_post_reviews')
    op.drop_table('change_post_reviews')
    op.drop_index(op.f('ix_change_implementations_status'), table_name='change_implementations')
    op.drop_index(op.f('ix_change_implementations_change_id'), table_name='change_implementations')
    op.drop_index('ix_change_implementation_change', table_name='change_implementations')
    op.drop_table('change_implementations')
    op.drop_index(op.f('ix_change_conflicts_status'), table_name='change_conflicts')
    op.drop_index(op.f('ix_change_conflicts_kind'), table_name='change_conflicts')
    op.drop_index(op.f('ix_change_conflicts_detected_at'), table_name='change_conflicts')
    op.drop_index(op.f('ix_change_conflicts_conflicting_change_id'), table_name='change_conflicts')
    op.drop_index(op.f('ix_change_conflicts_change_id'), table_name='change_conflicts')
    op.drop_index('ix_change_conflict_status', table_name='change_conflicts')
    op.drop_index('ix_change_conflict_change', table_name='change_conflicts')
    op.drop_table('change_conflicts')
    op.drop_index(op.f('ix_change_cab_status'), table_name='change_cab')
    op.drop_index(op.f('ix_change_cab_change_id'), table_name='change_cab')
    op.drop_index('ix_change_cab_change', table_name='change_cab')
    op.drop_table('change_cab')
    op.drop_index(op.f('ix_change_approvals_status'), table_name='change_approvals')
    op.drop_index(op.f('ix_change_approvals_expires_at'), table_name='change_approvals')
    op.drop_index(op.f('ix_change_approvals_change_id'), table_name='change_approvals')
    op.drop_index('ix_change_approval_status', table_name='change_approvals')
    op.drop_index('ix_change_approval_change', table_name='change_approvals')
    op.drop_table('change_approvals')
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_scheduled_start_at'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_risk_level'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_priority'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_incident_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_change_type'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_category'), table_name='change_requests')
    op.drop_index('ix_change_org_status', table_name='change_requests')
    op.drop_index('ix_change_org_priority', table_name='change_requests')
    op.drop_index('ix_change_org_created', table_name='change_requests')
    op.drop_index('ix_change_assignee', table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_change_types_change_type'), table_name='change_types')
    op.drop_table('change_types')
    op.drop_index(op.f('ix_change_status_status'), table_name='change_status')
    op.drop_table('change_status')
    op.drop_index(op.f('ix_change_statistics_window_start'), table_name='change_statistics')
    op.drop_index('ix_change_statistic_org', table_name='change_statistics')
    op.drop_table('change_statistics')
    op.drop_index(op.f('ix_change_priorities_priority'), table_name='change_priorities')
    op.drop_table('change_priorities')
    op.drop_index(op.f('ix_change_categories_slug'), table_name='change_categories')
    op.drop_index(op.f('ix_change_categories_category'), table_name='change_categories')
    op.drop_table('change_categories')
    op.drop_index(op.f('ix_change_calendar_starts_at'), table_name='change_calendar')
    op.drop_index(op.f('ix_change_calendar_kind'), table_name='change_calendar')
    op.drop_index(op.f('ix_change_calendar_ends_at'), table_name='change_calendar')
    op.drop_table('change_calendar')
    op.drop_index('ix_change_audit_org', table_name='change_audit')
    op.drop_index(op.f('ix_change_audit_occurred_at'), table_name='change_audit')
    op.drop_index(op.f('ix_change_audit_entity_type'), table_name='change_audit')
    op.drop_index(op.f('ix_change_audit_entity_id'), table_name='change_audit')
    op.drop_index(op.f('ix_change_audit_actor_id'), table_name='change_audit')
    op.drop_index('ix_change_audit_actor', table_name='change_audit')
    op.drop_index('ix_change_audit_action', table_name='change_audit')
    op.drop_table('change_audit')
    # ### end Alembic commands ###
