"""Plugin Framework constants.

Per docs/029_Enterprise_Plugin_Framework.md.txt. Default timing,
resource-limit, and versioning values every plugin inherits unless its
manifest overrides them.
"""

from __future__ import annotations

DEFAULT_SOURCE_SERVICE = "plugin-framework"

FRAMEWORK_VERSION = "1.0.0"

DEFAULT_INITIALIZE_TIMEOUT_SECONDS = 30.0
DEFAULT_START_TIMEOUT_SECONDS = 30.0
DEFAULT_STOP_TIMEOUT_SECONDS = 30.0
DEFAULT_EXECUTION_TIMEOUT_SECONDS = 60.0
DEFAULT_HOOK_TIMEOUT_SECONDS = 10.0

DEFAULT_MEMORY_LIMIT_MB = 256.0
DEFAULT_CPU_LIMIT_SECONDS = 30.0

DEFAULT_MAX_DEPENDENCY_DEPTH = 50

__all__ = [
    "DEFAULT_CPU_LIMIT_SECONDS",
    "DEFAULT_EXECUTION_TIMEOUT_SECONDS",
    "DEFAULT_HOOK_TIMEOUT_SECONDS",
    "DEFAULT_INITIALIZE_TIMEOUT_SECONDS",
    "DEFAULT_MAX_DEPENDENCY_DEPTH",
    "DEFAULT_MEMORY_LIMIT_MB",
    "DEFAULT_SOURCE_SERVICE",
    "DEFAULT_START_TIMEOUT_SECONDS",
    "DEFAULT_STOP_TIMEOUT_SECONDS",
    "FRAMEWORK_VERSION",
]
