"""compliance service schema

Revision ID: 477945dff7fb
Revises: 
Create Date: 2026-07-31 11:54:12.472853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477945dff7fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_audit',
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_audit_action', 'compliance_audit', ['organization_id', 'action'], unique=False)
    op.create_index('ix_compliance_audit_actor', 'compliance_audit', ['organization_id', 'actor_id'], unique=False)
    op.create_index(op.f('ix_compliance_audit_actor_id'), 'compliance_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_compliance_audit_entity_id'), 'compliance_audit', ['entity_id'], unique=False)
    op.create_index(op.f('ix_compliance_audit_entity_type'), 'compliance_audit', ['entity_type'], unique=False)
    op.create_index(op.f('ix_compliance_audit_occurred_at'), 'compliance_audit', ['occurred_at'], unique=False)
    op.create_index('ix_compliance_audit_org', 'compliance_audit', ['organization_id', 'occurred_at'], unique=False)
    op.create_table('compliance_frameworks',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('framework_version', sa.String(length=64), nullable=False),
    sa.Column('reference_url', sa.String(length=1024), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('control_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_compliance_framework_slug')
    )
    op.create_index('ix_compliance_framework_code', 'compliance_frameworks', ['organization_id', 'code'], unique=False)
    op.create_index('ix_compliance_framework_org', 'compliance_frameworks', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_compliance_frameworks_code'), 'compliance_frameworks', ['code'], unique=False)
    op.create_index(op.f('ix_compliance_frameworks_is_builtin'), 'compliance_frameworks', ['is_builtin'], unique=False)
    op.create_index(op.f('ix_compliance_frameworks_status'), 'compliance_frameworks', ['status'], unique=False)
    op.create_table('compliance_history',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=255), nullable=True),
    sa.Column('field', sa.String(length=128), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_history_entity', 'compliance_history', ['organization_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_compliance_history_entity_id'), 'compliance_history', ['entity_id'], unique=False)
    op.create_index(op.f('ix_compliance_history_entity_type'), 'compliance_history', ['entity_type'], unique=False)
    op.create_index('ix_compliance_history_org', 'compliance_history', ['organization_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_compliance_history_recorded_at'), 'compliance_history', ['recorded_at'], unique=False)
    op.create_table('compliance_risk_register',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('likelihood', sa.String(length=32), nullable=False),
    sa.Column('impact', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('inherent_score', sa.Float(), nullable=False),
    sa.Column('residual_likelihood', sa.String(length=32), nullable=True),
    sa.Column('residual_impact', sa.String(length=32), nullable=True),
    sa.Column('residual_severity', sa.String(length=32), nullable=True),
    sa.Column('residual_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('owner_team', sa.String(length=255), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('mitigation_status', sa.String(length=255), nullable=True),
    sa.Column('treatment', sa.String(length=64), nullable=True),
    sa.Column('control_ids', sa.JSON(), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=False),
    sa.Column('identified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_interval_days', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_reason', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'reference', name='uq_compliance_risk_reference')
    )
    op.create_index('ix_compliance_risk_org', 'compliance_risk_register', ['organization_id', 'status', 'severity'], unique=False)
    op.create_index('ix_compliance_risk_owner', 'compliance_risk_register', ['organization_id', 'owner_id'], unique=False)
    op.create_index(op.f('ix_compliance_risk_register_category'), 'compliance_risk_register', ['category'], unique=False)
    op.create_index(op.f('ix_compliance_risk_register_identified_at'), 'compliance_risk_register', ['identified_at'], unique=False)
    op.create_index(op.f('ix_compliance_risk_register_next_review_at'), 'compliance_risk_register', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_compliance_risk_register_residual_severity'), 'compliance_risk_register', ['residual_severity'], unique=False)
    op.create_index(op.f('ix_compliance_risk_register_severity'), 'compliance_risk_register', ['severity'], unique=False)
    op.create_index(op.f('ix_compliance_risk_register_status'), 'compliance_risk_register', ['status'], unique=False)
    op.create_index('ix_compliance_risk_review', 'compliance_risk_register', ['organization_id', 'next_review_at'], unique=False)
    op.create_table('compliance_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assessments_run', sa.Integer(), nullable=False),
    sa.Column('assessments_failed', sa.Integer(), nullable=False),
    sa.Column('scans_run', sa.Integer(), nullable=False),
    sa.Column('controls_evaluated', sa.Integer(), nullable=False),
    sa.Column('evidence_collected', sa.Integer(), nullable=False),
    sa.Column('findings_opened', sa.Integer(), nullable=False),
    sa.Column('findings_resolved', sa.Integer(), nullable=False),
    sa.Column('findings_open_total', sa.Integer(), nullable=False),
    sa.Column('findings_critical', sa.Integer(), nullable=False),
    sa.Column('risks_registered', sa.Integer(), nullable=False),
    sa.Column('risks_open_total', sa.Integer(), nullable=False),
    sa.Column('exceptions_active', sa.Integer(), nullable=False),
    sa.Column('exceptions_expiring', sa.Integer(), nullable=False),
    sa.Column('remediations_completed', sa.Integer(), nullable=False),
    sa.Column('remediations_verified', sa.Integer(), nullable=False),
    sa.Column('remediation_success_rate', sa.Float(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('framework_coverage', sa.Float(), nullable=False),
    sa.Column('control_coverage', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_statistic_org', 'compliance_statistics', ['organization_id', 'window_start'], unique=False)
    op.create_index(op.f('ix_compliance_statistics_window_start'), 'compliance_statistics', ['window_start'], unique=False)
    op.create_table('compliance_assessments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('framework_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('controls_total', sa.Integer(), nullable=False),
    sa.Column('controls_passed', sa.Integer(), nullable=False),
    sa.Column('controls_failed', sa.Integer(), nullable=False),
    sa.Column('controls_warning', sa.Integer(), nullable=False),
    sa.Column('controls_not_applicable', sa.Integer(), nullable=False),
    sa.Column('controls_not_assessed', sa.Integer(), nullable=False),
    sa.Column('controls_errored', sa.Integer(), nullable=False),
    sa.Column('controls_excepted', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('findings_raised', sa.Integer(), nullable=False),
    sa.Column('evidence_collected', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_assessment_framework', 'compliance_assessments', ['organization_id', 'framework_id'], unique=False)
    op.create_index('ix_compliance_assessment_org', 'compliance_assessments', ['organization_id', 'started_at'], unique=False)
    op.create_index('ix_compliance_assessment_status', 'compliance_assessments', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_framework_id'), 'compliance_assessments', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_scope'), 'compliance_assessments', ['scope'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_scope_id'), 'compliance_assessments', ['scope_id'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_status'), 'compliance_assessments', ['status'], unique=False)
    op.create_table('compliance_controls',
    sa.Column('framework_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('owner_team', sa.String(length=255), nullable=True),
    sa.Column('control_version', sa.Integer(), nullable=False),
    sa.Column('parent_control_id', sa.Uuid(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_automatable', sa.Boolean(), nullable=False),
    sa.Column('rule', sa.JSON(), nullable=False),
    sa.Column('remediation_guidance', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_control_id'], ['compliance_controls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'framework_id', 'code', name='uq_compliance_control_code')
    )
    op.create_index('ix_compliance_control_category', 'compliance_controls', ['organization_id', 'category'], unique=False)
    op.create_index('ix_compliance_control_framework', 'compliance_controls', ['organization_id', 'framework_id', 'status'], unique=False)
    op.create_index('ix_compliance_control_owner', 'compliance_controls', ['organization_id', 'owner_id'], unique=False)
    op.create_index(op.f('ix_compliance_controls_category'), 'compliance_controls', ['category'], unique=False)
    op.create_index(op.f('ix_compliance_controls_framework_id'), 'compliance_controls', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_controls_is_automatable'), 'compliance_controls', ['is_automatable'], unique=False)
    op.create_index(op.f('ix_compliance_controls_parent_control_id'), 'compliance_controls', ['parent_control_id'], unique=False)
    op.create_index(op.f('ix_compliance_controls_severity'), 'compliance_controls', ['severity'], unique=False)
    op.create_index(op.f('ix_compliance_controls_status'), 'compliance_controls', ['status'], unique=False)
    op.create_table('compliance_control_mappings',
    sa.Column('source_control_id', sa.Uuid(), nullable=False),
    sa.Column('target_control_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['source_control_id'], ['compliance_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_control_id'], ['compliance_controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_control_id', 'target_control_id', 'relation', name='uq_compliance_control_mapping')
    )
    op.create_index(op.f('ix_compliance_control_mappings_source_control_id'), 'compliance_control_mappings', ['source_control_id'], unique=False)
    op.create_index(op.f('ix_compliance_control_mappings_target_control_id'), 'compliance_control_mappings', ['target_control_id'], unique=False)
    op.create_index('ix_compliance_mapping_source', 'compliance_control_mappings', ['organization_id', 'source_control_id'], unique=False)
    op.create_index('ix_compliance_mapping_target', 'compliance_control_mappings', ['organization_id', 'target_control_id'], unique=False)
    op.create_table('compliance_evidence',
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('control_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_by', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_id'], ['compliance_controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['compliance_evidence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_evidence_assessment', 'compliance_evidence', ['organization_id', 'assessment_id'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_assessment_id'), 'compliance_evidence', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_collected_at'), 'compliance_evidence', ['collected_at'], unique=False)
    op.create_index('ix_compliance_evidence_control', 'compliance_evidence', ['organization_id', 'control_id'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_control_id'), 'compliance_evidence', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_digest'), 'compliance_evidence', ['digest'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_is_superseded'), 'compliance_evidence', ['is_superseded'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_kind'), 'compliance_evidence', ['kind'], unique=False)
    op.create_index('ix_compliance_evidence_org', 'compliance_evidence', ['organization_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_source'), 'compliance_evidence', ['source'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_target_id'), 'compliance_evidence', ['target_id'], unique=False)
    op.create_table('compliance_exceptions',
    sa.Column('control_id', sa.Uuid(), nullable=False),
    sa.Column('framework_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('business_justification', sa.Text(), nullable=False),
    sa.Column('risk_acceptance', sa.Text(), nullable=True),
    sa.Column('compensating_control', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_interval_days', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=255), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['compliance_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_exception_control', 'compliance_exceptions', ['organization_id', 'control_id'], unique=False)
    op.create_index('ix_compliance_exception_expiry', 'compliance_exceptions', ['organization_id', 'expires_at'], unique=False)
    op.create_index('ix_compliance_exception_org', 'compliance_exceptions', ['organization_id', 'status'], unique=False)
    op.create_index('ix_compliance_exception_review', 'compliance_exceptions', ['organization_id', 'next_review_at'], unique=False)
    op.create_index(op.f('ix_compliance_exceptions_control_id'), 'compliance_exceptions', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_exceptions_expires_at'), 'compliance_exceptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_compliance_exceptions_next_review_at'), 'compliance_exceptions', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_compliance_exceptions_status'), 'compliance_exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_compliance_exceptions_target_id'), 'compliance_exceptions', ['target_id'], unique=False)
    op.create_table('compliance_reports',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('framework_id', sa.Uuid(), nullable=True),
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_report_org', 'compliance_reports', ['organization_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_compliance_reports_generated_at'), 'compliance_reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_compliance_reports_kind'), 'compliance_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_compliance_reports_status'), 'compliance_reports', ['status'], unique=False)
    op.create_table('compliance_scans',
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('scanner', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('targets_scanned', sa.Integer(), nullable=False),
    sa.Column('checks_run', sa.Integer(), nullable=False),
    sa.Column('checks_failed', sa.Integer(), nullable=False),
    sa.Column('is_incremental', sa.Boolean(), nullable=False),
    sa.Column('baseline_scan_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['baseline_scan_id'], ['compliance_scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_scan_assessment', 'compliance_scans', ['organization_id', 'assessment_id'], unique=False)
    op.create_index('ix_compliance_scan_org', 'compliance_scans', ['organization_id', 'started_at'], unique=False)
    op.create_index('ix_compliance_scan_status', 'compliance_scans', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_compliance_scans_assessment_id'), 'compliance_scans', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_compliance_scans_kind'), 'compliance_scans', ['kind'], unique=False)
    op.create_index(op.f('ix_compliance_scans_status'), 'compliance_scans', ['status'], unique=False)
    op.create_index(op.f('ix_compliance_scans_target_id'), 'compliance_scans', ['target_id'], unique=False)
    op.create_table('compliance_scores',
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=255), nullable=True),
    sa.Column('scope_name', sa.String(length=512), nullable=True),
    sa.Column('framework_id', sa.Uuid(), nullable=True),
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('raw_pass_rate', sa.Float(), nullable=False),
    sa.Column('controls_total', sa.Integer(), nullable=False),
    sa.Column('controls_passed', sa.Integer(), nullable=False),
    sa.Column('controls_failed', sa.Integer(), nullable=False),
    sa.Column('controls_excepted', sa.Integer(), nullable=False),
    sa.Column('controls_not_applicable', sa.Integer(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_score_org', 'compliance_scores', ['organization_id', 'computed_at'], unique=False)
    op.create_index('ix_compliance_score_scope', 'compliance_scores', ['organization_id', 'scope', 'scope_id'], unique=False)
    op.create_index(op.f('ix_compliance_scores_computed_at'), 'compliance_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_compliance_scores_framework_id'), 'compliance_scores', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_scores_scope'), 'compliance_scores', ['scope'], unique=False)
    op.create_index(op.f('ix_compliance_scores_scope_id'), 'compliance_scores', ['scope_id'], unique=False)
    op.create_table('compliance_results',
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('control_id', sa.Uuid(), nullable=False),
    sa.Column('framework_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('target_name', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expected', sa.JSON(), nullable=False),
    sa.Column('observed', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('evidence_id', sa.Uuid(), nullable=True),
    sa.Column('exception_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['control_id'], ['compliance_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['compliance_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exception_id'], ['compliance_exceptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['compliance_scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_result_assessment', 'compliance_results', ['organization_id', 'assessment_id'], unique=False)
    op.create_index('ix_compliance_result_control', 'compliance_results', ['organization_id', 'control_id', 'status'], unique=False)
    op.create_index('ix_compliance_result_evaluated', 'compliance_results', ['organization_id', 'evaluated_at'], unique=False)
    op.create_index('ix_compliance_result_target', 'compliance_results', ['organization_id', 'target_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_assessment_id'), 'compliance_results', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_control_id'), 'compliance_results', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_framework_id'), 'compliance_results', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_scan_id'), 'compliance_results', ['scan_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_status'), 'compliance_results', ['status'], unique=False)
    op.create_table('compliance_findings',
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('control_id', sa.Uuid(), nullable=False),
    sa.Column('framework_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('target_name', sa.String(length=512), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('assignee_id', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=True),
    sa.Column('risk_id', sa.Uuid(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_id'], ['compliance_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exception_id'], ['compliance_exceptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['result_id'], ['compliance_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_id'], ['compliance_risk_register.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_finding_assignee', 'compliance_findings', ['organization_id', 'assignee_id'], unique=False)
    op.create_index('ix_compliance_finding_control', 'compliance_findings', ['organization_id', 'control_id'], unique=False)
    op.create_index('ix_compliance_finding_fingerprint', 'compliance_findings', ['organization_id', 'fingerprint'], unique=False)
    op.create_index('ix_compliance_finding_org', 'compliance_findings', ['organization_id', 'status', 'severity'], unique=False)
    op.create_index(op.f('ix_compliance_findings_assessment_id'), 'compliance_findings', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_compliance_findings_control_id'), 'compliance_findings', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_findings_fingerprint'), 'compliance_findings', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_compliance_findings_first_detected_at'), 'compliance_findings', ['first_detected_at'], unique=False)
    op.create_index(op.f('ix_compliance_findings_framework_id'), 'compliance_findings', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_findings_last_detected_at'), 'compliance_findings', ['last_detected_at'], unique=False)
    op.create_index(op.f('ix_compliance_findings_severity'), 'compliance_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_compliance_findings_status'), 'compliance_findings', ['status'], unique=False)
    op.create_index(op.f('ix_compliance_findings_target_id'), 'compliance_findings', ['target_id'], unique=False)
    op.create_table('compliance_remediation',
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.Column('control_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('playbook_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('automation_job_id', sa.String(length=255), nullable=True),
    sa.Column('configuration_reference', sa.String(length=512), nullable=True),
    sa.Column('assignee_id', sa.String(length=255), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verification_result_id', sa.Uuid(), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['compliance_controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['compliance_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_result_id'], ['compliance_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_remediation_assignee', 'compliance_remediation', ['organization_id', 'assignee_id'], unique=False)
    op.create_index(op.f('ix_compliance_remediation_control_id'), 'compliance_remediation', ['control_id'], unique=False)
    op.create_index('ix_compliance_remediation_finding', 'compliance_remediation', ['organization_id', 'finding_id'], unique=False)
    op.create_index(op.f('ix_compliance_remediation_finding_id'), 'compliance_remediation', ['finding_id'], unique=False)
    op.create_index('ix_compliance_remediation_org', 'compliance_remediation', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_compliance_remediation_status'), 'compliance_remediation', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_remediation_status'), table_name='compliance_remediation')
    op.drop_index('ix_compliance_remediation_org', table_name='compliance_remediation')
    op.drop_index(op.f('ix_compliance_remediation_finding_id'), table_name='compliance_remediation')
    op.drop_index('ix_compliance_remediation_finding', table_name='compliance_remediation')
    op.drop_index(op.f('ix_compliance_remediation_control_id'), table_name='compliance_remediation')
    op.drop_index('ix_compliance_remediation_assignee', table_name='compliance_remediation')
    op.drop_table('compliance_remediation')
    op.drop_index(op.f('ix_compliance_findings_target_id'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_status'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_severity'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_last_detected_at'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_framework_id'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_first_detected_at'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_fingerprint'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_control_id'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_assessment_id'), table_name='compliance_findings')
    op.drop_index('ix_compliance_finding_org', table_name='compliance_findings')
    op.drop_index('ix_compliance_finding_fingerprint', table_name='compliance_findings')
    op.drop_index('ix_compliance_finding_control', table_name='compliance_findings')
    op.drop_index('ix_compliance_finding_assignee', table_name='compliance_findings')
    op.drop_table('compliance_findings')
    op.drop_index(op.f('ix_compliance_results_status'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_scan_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_framework_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_control_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_assessment_id'), table_name='compliance_results')
    op.drop_index('ix_compliance_result_target', table_name='compliance_results')
    op.drop_index('ix_compliance_result_evaluated', table_name='compliance_results')
    op.drop_index('ix_compliance_result_control', table_name='compliance_results')
    op.drop_index('ix_compliance_result_assessment', table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index(op.f('ix_compliance_scores_scope_id'), table_name='compliance_scores')
    op.drop_index(op.f('ix_compliance_scores_scope'), table_name='compliance_scores')
    op.drop_index(op.f('ix_compliance_scores_framework_id'), table_name='compliance_scores')
    op.drop_index(op.f('ix_compliance_scores_computed_at'), table_name='compliance_scores')
    op.drop_index('ix_compliance_score_scope', table_name='compliance_scores')
    op.drop_index('ix_compliance_score_org', table_name='compliance_scores')
    op.drop_table('compliance_scores')
    op.drop_index(op.f('ix_compliance_scans_target_id'), table_name='compliance_scans')
    op.drop_index(op.f('ix_compliance_scans_status'), table_name='compliance_scans')
    op.drop_index(op.f('ix_compliance_scans_kind'), table_name='compliance_scans')
    op.drop_index(op.f('ix_compliance_scans_assessment_id'), table_name='compliance_scans')
    op.drop_index('ix_compliance_scan_status', table_name='compliance_scans')
    op.drop_index('ix_compliance_scan_org', table_name='compliance_scans')
    op.drop_index('ix_compliance_scan_assessment', table_name='compliance_scans')
    op.drop_table('compliance_scans')
    op.drop_index(op.f('ix_compliance_reports_status'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_kind'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_generated_at'), table_name='compliance_reports')
    op.drop_index('ix_compliance_report_org', table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_index(op.f('ix_compliance_exceptions_target_id'), table_name='compliance_exceptions')
    op.drop_index(op.f('ix_compliance_exceptions_status'), table_name='compliance_exceptions')
    op.drop_index(op.f('ix_compliance_exceptions_next_review_at'), table_name='compliance_exceptions')
    op.drop_index(op.f('ix_compliance_exceptions_expires_at'), table_name='compliance_exceptions')
    op.drop_index(op.f('ix_compliance_exceptions_control_id'), table_name='compliance_exceptions')
    op.drop_index('ix_compliance_exception_review', table_name='compliance_exceptions')
    op.drop_index('ix_compliance_exception_org', table_name='compliance_exceptions')
    op.drop_index('ix_compliance_exception_expiry', table_name='compliance_exceptions')
    op.drop_index('ix_compliance_exception_control', table_name='compliance_exceptions')
    op.drop_table('compliance_exceptions')
    op.drop_index(op.f('ix_compliance_evidence_target_id'), table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_source'), table_name='compliance_evidence')
    op.drop_index('ix_compliance_evidence_org', table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_kind'), table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_is_superseded'), table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_digest'), table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_control_id'), table_name='compliance_evidence')
    op.drop_index('ix_compliance_evidence_control', table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_collected_at'), table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_assessment_id'), table_name='compliance_evidence')
    op.drop_index('ix_compliance_evidence_assessment', table_name='compliance_evidence')
    op.drop_table('compliance_evidence')
    op.drop_index('ix_compliance_mapping_target', table_name='compliance_control_mappings')
    op.drop_index('ix_compliance_mapping_source', table_name='compliance_control_mappings')
    op.drop_index(op.f('ix_compliance_control_mappings_target_control_id'), table_name='compliance_control_mappings')
    op.drop_index(op.f('ix_compliance_control_mappings_source_control_id'), table_name='compliance_control_mappings')
    op.drop_table('compliance_control_mappings')
    op.drop_index(op.f('ix_compliance_controls_status'), table_name='compliance_controls')
    op.drop_index(op.f('ix_compliance_controls_severity'), table_name='compliance_controls')
    op.drop_index(op.f('ix_compliance_controls_parent_control_id'), table_name='compliance_controls')
    op.drop_index(op.f('ix_compliance_controls_is_automatable'), table_name='compliance_controls')
    op.drop_index(op.f('ix_compliance_controls_framework_id'), table_name='compliance_controls')
    op.drop_index(op.f('ix_compliance_controls_category'), table_name='compliance_controls')
    op.drop_index('ix_compliance_control_owner', table_name='compliance_controls')
    op.drop_index('ix_compliance_control_framework', table_name='compliance_controls')
    op.drop_index('ix_compliance_control_category', table_name='compliance_controls')
    op.drop_table('compliance_controls')
    op.drop_index(op.f('ix_compliance_assessments_status'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_scope_id'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_scope'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_framework_id'), table_name='compliance_assessments')
    op.drop_index('ix_compliance_assessment_status', table_name='compliance_assessments')
    op.drop_index('ix_compliance_assessment_org', table_name='compliance_assessments')
    op.drop_index('ix_compliance_assessment_framework', table_name='compliance_assessments')
    op.drop_table('compliance_assessments')
    op.drop_index(op.f('ix_compliance_statistics_window_start'), table_name='compliance_statistics')
    op.drop_index('ix_compliance_statistic_org', table_name='compliance_statistics')
    op.drop_table('compliance_statistics')
    op.drop_index('ix_compliance_risk_review', table_name='compliance_risk_register')
    op.drop_index(op.f('ix_compliance_risk_register_status'), table_name='compliance_risk_register')
    op.drop_index(op.f('ix_compliance_risk_register_severity'), table_name='compliance_risk_register')
    op.drop_index(op.f('ix_compliance_risk_register_residual_severity'), table_name='compliance_risk_register')
    op.drop_index(op.f('ix_compliance_risk_register_next_review_at'), table_name='compliance_risk_register')
    op.drop_index(op.f('ix_compliance_risk_register_identified_at'), table_name='compliance_risk_register')
    op.drop_index(op.f('ix_compliance_risk_register_category'), table_name='compliance_risk_register')
    op.drop_index('ix_compliance_risk_owner', table_name='compliance_risk_register')
    op.drop_index('ix_compliance_risk_org', table_name='compliance_risk_register')
    op.drop_table('compliance_risk_register')
    op.drop_index(op.f('ix_compliance_history_recorded_at'), table_name='compliance_history')
    op.drop_index('ix_compliance_history_org', table_name='compliance_history')
    op.drop_index(op.f('ix_compliance_history_entity_type'), table_name='compliance_history')
    op.drop_index(op.f('ix_compliance_history_entity_id'), table_name='compliance_history')
    op.drop_index('ix_compliance_history_entity', table_name='compliance_history')
    op.drop_table('compliance_history')
    op.drop_index(op.f('ix_compliance_frameworks_status'), table_name='compliance_frameworks')
    op.drop_index(op.f('ix_compliance_frameworks_is_builtin'), table_name='compliance_frameworks')
    op.drop_index(op.f('ix_compliance_frameworks_code'), table_name='compliance_frameworks')
    op.drop_index('ix_compliance_framework_org', table_name='compliance_frameworks')
    op.drop_index('ix_compliance_framework_code', table_name='compliance_frameworks')
    op.drop_table('compliance_frameworks')
    op.drop_index('ix_compliance_audit_org', table_name='compliance_audit')
    op.drop_index(op.f('ix_compliance_audit_occurred_at'), table_name='compliance_audit')
    op.drop_index(op.f('ix_compliance_audit_entity_type'), table_name='compliance_audit')
    op.drop_index(op.f('ix_compliance_audit_entity_id'), table_name='compliance_audit')
    op.drop_index(op.f('ix_compliance_audit_actor_id'), table_name='compliance_audit')
    op.drop_index('ix_compliance_audit_actor', table_name='compliance_audit')
    op.drop_index('ix_compliance_audit_action', table_name='compliance_audit')
    op.drop_table('compliance_audit')
    # ### end Alembic commands ###
