"""initial workflow runtime schema

Revision ID: 205e81d6a3b3
Revises: 
Create Date: 2026-07-27 11:40:35.482783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205e81d6a3b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('workflow_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('default_variables', sa.JSON(), nullable=False),
    sa.Column('current_version_number', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_workflow_key'), 'workflow_definitions', ['workflow_key'], unique=False)
    op.create_table('workflow_statistics',
    sa.Column('total_workflows', sa.Integer(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('average_duration_seconds', sa.Float(), nullable=False),
    sa.Column('checkpoint_count', sa.Integer(), nullable=False),
    sa.Column('approval_count', sa.Integer(), nullable=False),
    sa.Column('replay_count', sa.Integer(), nullable=False),
    sa.Column('rollback_count', sa.Integer(), nullable=False),
    sa.Column('node_statistics', sa.JSON(), nullable=False),
    sa.Column('execution_trends', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_workflow_statistics_org')
    )
    op.create_table('workflow_versions',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.String(length=32), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('compiled_execution_plan', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_versions_definition_id'), 'workflow_versions', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflow_versions_version_number'), 'workflow_versions', ['version_number'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('parent_instance_id', sa.Uuid(), nullable=True),
    sa.Column('sdk_execution_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_instance_id'], ['workflow_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['workflow_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_definition_id'), 'workflow_instances', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_parent_instance_id'), 'workflow_instances', ['parent_instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_sdk_execution_id'), 'workflow_instances', ['sdk_execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_status'), 'workflow_instances', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_version_id'), 'workflow_instances', ['version_id'], unique=False)
    op.create_table('workflow_approvals',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('approvers', sa.JSON(), nullable=False),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decisions_by_approver', sa.JSON(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('escalated_to', sa.String(length=255), nullable=True),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_approvals_decision'), 'workflow_approvals', ['decision'], unique=False)
    op.create_index(op.f('ix_workflow_approvals_instance_id'), 'workflow_approvals', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_approvals_node_id'), 'workflow_approvals', ['node_id'], unique=False)
    op.create_table('workflow_audit',
    sa.Column('instance_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_audit_instance_id'), 'workflow_audit', ['instance_id'], unique=False)
    op.create_table('workflow_checkpoints',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('completed_node_ids', sa.JSON(), nullable=False),
    sa.Column('variables_snapshot', sa.JSON(), nullable=False),
    sa.Column('checkpointed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_checkpoints_instance_id'), 'workflow_checkpoints', ['instance_id'], unique=False)
    op.create_table('workflow_compensation',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_compensation_instance_id'), 'workflow_compensation', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_compensation_node_id'), 'workflow_compensation', ['node_id'], unique=False)
    op.create_table('workflow_context',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_context_instance_id'), 'workflow_context', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_context_key'), 'workflow_context', ['key'], unique=False)
    op.create_table('workflow_events',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_event_type'), 'workflow_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_workflow_events_instance_id'), 'workflow_events', ['instance_id'], unique=False)
    op.create_table('workflow_execution_steps',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_execution_steps_instance_id'), 'workflow_execution_steps', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_steps_node_id'), 'workflow_execution_steps', ['node_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_steps_status'), 'workflow_execution_steps', ['status'], unique=False)
    op.create_table('workflow_logs',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_logs_instance_id'), 'workflow_logs', ['instance_id'], unique=False)
    op.create_table('workflow_reports',
    sa.Column('instance_id', sa.Uuid(), nullable=True),
    sa.Column('report_type', sa.String(length=24), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_reports_instance_id'), 'workflow_reports', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_reports_report_type'), 'workflow_reports', ['report_type'], unique=False)
    op.create_table('workflow_results',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_results_instance_id'), 'workflow_results', ['instance_id'], unique=False)
    op.create_table('workflow_states',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('transitioned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_states_instance_id'), 'workflow_states', ['instance_id'], unique=False)
    op.create_table('workflow_timers',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=True),
    sa.Column('node_id', sa.String(length=255), nullable=True),
    sa.Column('timer_type', sa.String(length=16), nullable=False),
    sa.Column('cron_expression', sa.String(length=128), nullable=True),
    sa.Column('fires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_timers_definition_id'), 'workflow_timers', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflow_timers_instance_id'), 'workflow_timers', ['instance_id'], unique=False)
    op.create_table('workflow_variables',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_variables_definition_id'), 'workflow_variables', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflow_variables_instance_id'), 'workflow_variables', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_variables_name'), 'workflow_variables', ['name'], unique=False)
    op.create_table('workflow_replay',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('new_instance_id', sa.Uuid(), nullable=False),
    sa.Column('replay_type', sa.String(length=16), nullable=False),
    sa.Column('source_checkpoint_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comparison', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_checkpoint_id'], ['workflow_checkpoints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_replay_instance_id'), 'workflow_replay', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_replay_new_instance_id'), 'workflow_replay', ['new_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_replay_new_instance_id'), table_name='workflow_replay')
    op.drop_index(op.f('ix_workflow_replay_instance_id'), table_name='workflow_replay')
    op.drop_table('workflow_replay')
    op.drop_index(op.f('ix_workflow_variables_name'), table_name='workflow_variables')
    op.drop_index(op.f('ix_workflow_variables_instance_id'), table_name='workflow_variables')
    op.drop_index(op.f('ix_workflow_variables_definition_id'), table_name='workflow_variables')
    op.drop_table('workflow_variables')
    op.drop_index(op.f('ix_workflow_timers_instance_id'), table_name='workflow_timers')
    op.drop_index(op.f('ix_workflow_timers_definition_id'), table_name='workflow_timers')
    op.drop_table('workflow_timers')
    op.drop_index(op.f('ix_workflow_states_instance_id'), table_name='workflow_states')
    op.drop_table('workflow_states')
    op.drop_index(op.f('ix_workflow_results_instance_id'), table_name='workflow_results')
    op.drop_table('workflow_results')
    op.drop_index(op.f('ix_workflow_reports_report_type'), table_name='workflow_reports')
    op.drop_index(op.f('ix_workflow_reports_instance_id'), table_name='workflow_reports')
    op.drop_table('workflow_reports')
    op.drop_index(op.f('ix_workflow_logs_instance_id'), table_name='workflow_logs')
    op.drop_table('workflow_logs')
    op.drop_index(op.f('ix_workflow_execution_steps_status'), table_name='workflow_execution_steps')
    op.drop_index(op.f('ix_workflow_execution_steps_node_id'), table_name='workflow_execution_steps')
    op.drop_index(op.f('ix_workflow_execution_steps_instance_id'), table_name='workflow_execution_steps')
    op.drop_table('workflow_execution_steps')
    op.drop_index(op.f('ix_workflow_events_instance_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_event_type'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_workflow_context_key'), table_name='workflow_context')
    op.drop_index(op.f('ix_workflow_context_instance_id'), table_name='workflow_context')
    op.drop_table('workflow_context')
    op.drop_index(op.f('ix_workflow_compensation_node_id'), table_name='workflow_compensation')
    op.drop_index(op.f('ix_workflow_compensation_instance_id'), table_name='workflow_compensation')
    op.drop_table('workflow_compensation')
    op.drop_index(op.f('ix_workflow_checkpoints_instance_id'), table_name='workflow_checkpoints')
    op.drop_table('workflow_checkpoints')
    op.drop_index(op.f('ix_workflow_audit_instance_id'), table_name='workflow_audit')
    op.drop_table('workflow_audit')
    op.drop_index(op.f('ix_workflow_approvals_node_id'), table_name='workflow_approvals')
    op.drop_index(op.f('ix_workflow_approvals_instance_id'), table_name='workflow_approvals')
    op.drop_index(op.f('ix_workflow_approvals_decision'), table_name='workflow_approvals')
    op.drop_table('workflow_approvals')
    op.drop_index(op.f('ix_workflow_instances_version_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_status'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_sdk_execution_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_parent_instance_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_definition_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_workflow_versions_version_number'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_definition_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_table('workflow_statistics')
    op.drop_index(op.f('ix_workflow_definitions_workflow_key'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
