"""initial configuration management schema

Revision ID: 5762fe9f4ca9
Revises: 
Create Date: 2026-07-24 20:40:36.205087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5762fe9f4ca9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_environments',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('environment_type', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_configuration_environment_name')
    )
    op.create_index(op.f('ix_configuration_environments_environment_type'), 'configuration_environments', ['environment_type'], unique=False)
    op.create_index(op.f('ix_configuration_environments_name'), 'configuration_environments', ['name'], unique=False)
    op.create_table('configuration_policies',
    sa.Column('policy_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('rule', sa.JSON(), nullable=False),
    sa.Column('enforced', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_configuration_policy_name')
    )
    op.create_index(op.f('ix_configuration_policies_name'), 'configuration_policies', ['name'], unique=False)
    op.create_index(op.f('ix_configuration_policies_policy_type'), 'configuration_policies', ['policy_type'], unique=False)
    op.create_table('configuration_profiles',
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('profile_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('environment', sa.String(length=24), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('configuration_type', sa.String(length=24), nullable=False),
    sa.Column('target_assets', sa.JSON(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_profiles_configuration_type'), 'configuration_profiles', ['configuration_type'], unique=False)
    op.create_index(op.f('ix_configuration_profiles_environment'), 'configuration_profiles', ['environment'], unique=False)
    op.create_index(op.f('ix_configuration_profiles_profile_name'), 'configuration_profiles', ['profile_name'], unique=False)
    op.create_index(op.f('ix_configuration_profiles_status'), 'configuration_profiles', ['status'], unique=False)
    op.create_table('configuration_statistics',
    sa.Column('total_profiles', sa.Integer(), nullable=False),
    sa.Column('total_versions', sa.Integer(), nullable=False),
    sa.Column('drift_statistics', sa.JSON(), nullable=False),
    sa.Column('compliance_scores', sa.JSON(), nullable=False),
    sa.Column('rollback_statistics', sa.JSON(), nullable=False),
    sa.Column('deployment_readiness', sa.JSON(), nullable=False),
    sa.Column('environment_distribution', sa.JSON(), nullable=False),
    sa.Column('change_frequency', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_configuration_statistics_org')
    )
    op.create_table('configuration_templates',
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('configuration_type', sa.String(length=24), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables_schema', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_templates_configuration_type'), 'configuration_templates', ['configuration_type'], unique=False)
    op.create_index(op.f('ix_configuration_templates_template_name'), 'configuration_templates', ['template_name'], unique=False)
    op.create_table('configuration_variables',
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('scope_ref_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=4096), nullable=True),
    sa.Column('is_secret_reference', sa.Boolean(), nullable=False),
    sa.Column('is_computed', sa.Boolean(), nullable=False),
    sa.Column('validation_rule', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'scope', 'scope_ref_id', 'key', name='uq_configuration_variable_key')
    )
    op.create_index(op.f('ix_configuration_variables_key'), 'configuration_variables', ['key'], unique=False)
    op.create_index(op.f('ix_configuration_variables_scope'), 'configuration_variables', ['scope'], unique=False)
    op.create_index(op.f('ix_configuration_variables_scope_ref_id'), 'configuration_variables', ['scope_ref_id'], unique=False)
    op.create_table('configuration_ansible_inventories',
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inventory_content', sa.JSON(), nullable=False),
    sa.Column('host_vars', sa.JSON(), nullable=False),
    sa.Column('group_vars', sa.JSON(), nullable=False),
    sa.Column('playbooks', sa.JSON(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('collections', sa.JSON(), nullable=False),
    sa.Column('vault_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_ansible_inventories_name'), 'configuration_ansible_inventories', ['name'], unique=False)
    op.create_index(op.f('ix_configuration_ansible_inventories_profile_id'), 'configuration_ansible_inventories', ['profile_id'], unique=False)
    op.create_table('configuration_assignments',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('managed_asset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'managed_asset_id', name='uq_configuration_assignment_profile_asset')
    )
    op.create_index(op.f('ix_configuration_assignments_managed_asset_id'), 'configuration_assignments', ['managed_asset_id'], unique=False)
    op.create_index(op.f('ix_configuration_assignments_profile_id'), 'configuration_assignments', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_assignments_status'), 'configuration_assignments', ['status'], unique=False)
    op.create_table('configuration_audit',
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_audit_profile_id'), 'configuration_audit', ['profile_id'], unique=False)
    op.create_table('configuration_backups',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('backup_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_backups_backup_type'), 'configuration_backups', ['backup_type'], unique=False)
    op.create_index(op.f('ix_configuration_backups_profile_id'), 'configuration_backups', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_backups_status'), 'configuration_backups', ['status'], unique=False)
    op.create_table('configuration_baselines',
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('baseline_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('baseline_version', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_baselines_baseline_type'), 'configuration_baselines', ['baseline_type'], unique=False)
    op.create_index(op.f('ix_configuration_baselines_name'), 'configuration_baselines', ['name'], unique=False)
    op.create_index(op.f('ix_configuration_baselines_profile_id'), 'configuration_baselines', ['profile_id'], unique=False)
    op.create_table('configuration_change_sets',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_change_sets_profile_id'), 'configuration_change_sets', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_change_sets_status'), 'configuration_change_sets', ['status'], unique=False)
    op.create_table('configuration_compliance',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('eval_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('exception_reason', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_compliance_checked_at'), 'configuration_compliance', ['checked_at'], unique=False)
    op.create_index(op.f('ix_configuration_compliance_eval_type'), 'configuration_compliance', ['eval_type'], unique=False)
    op.create_index(op.f('ix_configuration_compliance_profile_id'), 'configuration_compliance', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_compliance_status'), 'configuration_compliance', ['status'], unique=False)
    op.create_table('configuration_drift',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('managed_asset_id', sa.Uuid(), nullable=False),
    sa.Column('drift_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_drift_detected_at'), 'configuration_drift', ['detected_at'], unique=False)
    op.create_index(op.f('ix_configuration_drift_drift_type'), 'configuration_drift', ['drift_type'], unique=False)
    op.create_index(op.f('ix_configuration_drift_managed_asset_id'), 'configuration_drift', ['managed_asset_id'], unique=False)
    op.create_index(op.f('ix_configuration_drift_profile_id'), 'configuration_drift', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_drift_status'), 'configuration_drift', ['status'], unique=False)
    op.create_table('configuration_git_repositories',
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('repository_url', sa.String(length=1024), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credential_ref', sa.String(length=255), nullable=True),
    sa.Column('webhook_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_git_repositories_profile_id'), 'configuration_git_repositories', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_git_repositories_provider'), 'configuration_git_repositories', ['provider'], unique=False)
    op.create_index(op.f('ix_configuration_git_repositories_sync_status'), 'configuration_git_repositories', ['sync_status'], unique=False)
    op.create_table('configuration_kubernetes_manifests',
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_kubernetes_manifests_format'), 'configuration_kubernetes_manifests', ['format'], unique=False)
    op.create_index(op.f('ix_configuration_kubernetes_manifests_name'), 'configuration_kubernetes_manifests', ['name'], unique=False)
    op.create_index(op.f('ix_configuration_kubernetes_manifests_profile_id'), 'configuration_kubernetes_manifests', ['profile_id'], unique=False)
    op.create_table('configuration_reports',
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('report_type', sa.String(length=24), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_reports_profile_id'), 'configuration_reports', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_reports_report_type'), 'configuration_reports', ['report_type'], unique=False)
    op.create_table('configuration_tosca_templates',
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('component_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('csar_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_tosca_templates_component_type'), 'configuration_tosca_templates', ['component_type'], unique=False)
    op.create_index(op.f('ix_configuration_tosca_templates_name'), 'configuration_tosca_templates', ['name'], unique=False)
    op.create_index(op.f('ix_configuration_tosca_templates_profile_id'), 'configuration_tosca_templates', ['profile_id'], unique=False)
    op.create_table('configuration_versions',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.String(length=32), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.String(length=2048), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_versions_branch'), 'configuration_versions', ['branch'], unique=False)
    op.create_index(op.f('ix_configuration_versions_profile_id'), 'configuration_versions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_versions_version_number'), 'configuration_versions', ['version_number'], unique=False)
    op.create_table('configuration_restore_jobs',
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('restore_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('preview_only', sa.Boolean(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['configuration_backups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_restore_jobs_backup_id'), 'configuration_restore_jobs', ['backup_id'], unique=False)
    op.create_index(op.f('ix_configuration_restore_jobs_profile_id'), 'configuration_restore_jobs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_restore_jobs_restore_type'), 'configuration_restore_jobs', ['restore_type'], unique=False)
    op.create_index(op.f('ix_configuration_restore_jobs_status'), 'configuration_restore_jobs', ['status'], unique=False)
    op.create_table('configuration_rollbacks',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('from_version_id', sa.Uuid(), nullable=True),
    sa.Column('to_version_id', sa.Uuid(), nullable=False),
    sa.Column('rollback_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['from_version_id'], ['configuration_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_version_id'], ['configuration_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_rollbacks_profile_id'), 'configuration_rollbacks', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_rollbacks_rollback_type'), 'configuration_rollbacks', ['rollback_type'], unique=False)
    op.create_index(op.f('ix_configuration_rollbacks_status'), 'configuration_rollbacks', ['status'], unique=False)
    op.create_table('configuration_approvals',
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('rollback_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('comments', sa.String(length=2048), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rollback_id'], ['configuration_rollbacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['configuration_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_approvals_profile_id'), 'configuration_approvals', ['profile_id'], unique=False)
    op.create_index(op.f('ix_configuration_approvals_rollback_id'), 'configuration_approvals', ['rollback_id'], unique=False)
    op.create_index(op.f('ix_configuration_approvals_status'), 'configuration_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_configuration_approvals_version_id'), 'configuration_approvals', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuration_approvals_version_id'), table_name='configuration_approvals')
    op.drop_index(op.f('ix_configuration_approvals_status'), table_name='configuration_approvals')
    op.drop_index(op.f('ix_configuration_approvals_rollback_id'), table_name='configuration_approvals')
    op.drop_index(op.f('ix_configuration_approvals_profile_id'), table_name='configuration_approvals')
    op.drop_table('configuration_approvals')
    op.drop_index(op.f('ix_configuration_rollbacks_status'), table_name='configuration_rollbacks')
    op.drop_index(op.f('ix_configuration_rollbacks_rollback_type'), table_name='configuration_rollbacks')
    op.drop_index(op.f('ix_configuration_rollbacks_profile_id'), table_name='configuration_rollbacks')
    op.drop_table('configuration_rollbacks')
    op.drop_index(op.f('ix_configuration_restore_jobs_status'), table_name='configuration_restore_jobs')
    op.drop_index(op.f('ix_configuration_restore_jobs_restore_type'), table_name='configuration_restore_jobs')
    op.drop_index(op.f('ix_configuration_restore_jobs_profile_id'), table_name='configuration_restore_jobs')
    op.drop_index(op.f('ix_configuration_restore_jobs_backup_id'), table_name='configuration_restore_jobs')
    op.drop_table('configuration_restore_jobs')
    op.drop_index(op.f('ix_configuration_versions_version_number'), table_name='configuration_versions')
    op.drop_index(op.f('ix_configuration_versions_profile_id'), table_name='configuration_versions')
    op.drop_index(op.f('ix_configuration_versions_branch'), table_name='configuration_versions')
    op.drop_table('configuration_versions')
    op.drop_index(op.f('ix_configuration_tosca_templates_profile_id'), table_name='configuration_tosca_templates')
    op.drop_index(op.f('ix_configuration_tosca_templates_name'), table_name='configuration_tosca_templates')
    op.drop_index(op.f('ix_configuration_tosca_templates_component_type'), table_name='configuration_tosca_templates')
    op.drop_table('configuration_tosca_templates')
    op.drop_index(op.f('ix_configuration_reports_report_type'), table_name='configuration_reports')
    op.drop_index(op.f('ix_configuration_reports_profile_id'), table_name='configuration_reports')
    op.drop_table('configuration_reports')
    op.drop_index(op.f('ix_configuration_kubernetes_manifests_profile_id'), table_name='configuration_kubernetes_manifests')
    op.drop_index(op.f('ix_configuration_kubernetes_manifests_name'), table_name='configuration_kubernetes_manifests')
    op.drop_index(op.f('ix_configuration_kubernetes_manifests_format'), table_name='configuration_kubernetes_manifests')
    op.drop_table('configuration_kubernetes_manifests')
    op.drop_index(op.f('ix_configuration_git_repositories_sync_status'), table_name='configuration_git_repositories')
    op.drop_index(op.f('ix_configuration_git_repositories_provider'), table_name='configuration_git_repositories')
    op.drop_index(op.f('ix_configuration_git_repositories_profile_id'), table_name='configuration_git_repositories')
    op.drop_table('configuration_git_repositories')
    op.drop_index(op.f('ix_configuration_drift_status'), table_name='configuration_drift')
    op.drop_index(op.f('ix_configuration_drift_profile_id'), table_name='configuration_drift')
    op.drop_index(op.f('ix_configuration_drift_managed_asset_id'), table_name='configuration_drift')
    op.drop_index(op.f('ix_configuration_drift_drift_type'), table_name='configuration_drift')
    op.drop_index(op.f('ix_configuration_drift_detected_at'), table_name='configuration_drift')
    op.drop_table('configuration_drift')
    op.drop_index(op.f('ix_configuration_compliance_status'), table_name='configuration_compliance')
    op.drop_index(op.f('ix_configuration_compliance_profile_id'), table_name='configuration_compliance')
    op.drop_index(op.f('ix_configuration_compliance_eval_type'), table_name='configuration_compliance')
    op.drop_index(op.f('ix_configuration_compliance_checked_at'), table_name='configuration_compliance')
    op.drop_table('configuration_compliance')
    op.drop_index(op.f('ix_configuration_change_sets_status'), table_name='configuration_change_sets')
    op.drop_index(op.f('ix_configuration_change_sets_profile_id'), table_name='configuration_change_sets')
    op.drop_table('configuration_change_sets')
    op.drop_index(op.f('ix_configuration_baselines_profile_id'), table_name='configuration_baselines')
    op.drop_index(op.f('ix_configuration_baselines_name'), table_name='configuration_baselines')
    op.drop_index(op.f('ix_configuration_baselines_baseline_type'), table_name='configuration_baselines')
    op.drop_table('configuration_baselines')
    op.drop_index(op.f('ix_configuration_backups_status'), table_name='configuration_backups')
    op.drop_index(op.f('ix_configuration_backups_profile_id'), table_name='configuration_backups')
    op.drop_index(op.f('ix_configuration_backups_backup_type'), table_name='configuration_backups')
    op.drop_table('configuration_backups')
    op.drop_index(op.f('ix_configuration_audit_profile_id'), table_name='configuration_audit')
    op.drop_table('configuration_audit')
    op.drop_index(op.f('ix_configuration_assignments_status'), table_name='configuration_assignments')
    op.drop_index(op.f('ix_configuration_assignments_profile_id'), table_name='configuration_assignments')
    op.drop_index(op.f('ix_configuration_assignments_managed_asset_id'), table_name='configuration_assignments')
    op.drop_table('configuration_assignments')
    op.drop_index(op.f('ix_configuration_ansible_inventories_profile_id'), table_name='configuration_ansible_inventories')
    op.drop_index(op.f('ix_configuration_ansible_inventories_name'), table_name='configuration_ansible_inventories')
    op.drop_table('configuration_ansible_inventories')
    op.drop_index(op.f('ix_configuration_variables_scope_ref_id'), table_name='configuration_variables')
    op.drop_index(op.f('ix_configuration_variables_scope'), table_name='configuration_variables')
    op.drop_index(op.f('ix_configuration_variables_key'), table_name='configuration_variables')
    op.drop_table('configuration_variables')
    op.drop_index(op.f('ix_configuration_templates_template_name'), table_name='configuration_templates')
    op.drop_index(op.f('ix_configuration_templates_configuration_type'), table_name='configuration_templates')
    op.drop_table('configuration_templates')
    op.drop_table('configuration_statistics')
    op.drop_index(op.f('ix_configuration_profiles_status'), table_name='configuration_profiles')
    op.drop_index(op.f('ix_configuration_profiles_profile_name'), table_name='configuration_profiles')
    op.drop_index(op.f('ix_configuration_profiles_environment'), table_name='configuration_profiles')
    op.drop_index(op.f('ix_configuration_profiles_configuration_type'), table_name='configuration_profiles')
    op.drop_table('configuration_profiles')
    op.drop_index(op.f('ix_configuration_policies_policy_type'), table_name='configuration_policies')
    op.drop_index(op.f('ix_configuration_policies_name'), table_name='configuration_policies')
    op.drop_table('configuration_policies')
    op.drop_index(op.f('ix_configuration_environments_name'), table_name='configuration_environments')
    op.drop_index(op.f('ix_configuration_environments_environment_type'), table_name='configuration_environments')
    op.drop_table('configuration_environments')
    # ### end Alembic commands ###
