"""initial inventory schema

Revision ID: 8974a8dd7ee7
Revises:
Create Date: 2026-07-23 16:47:14.793246

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8974a8dd7ee7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:  # noqa: PLR0915 -- 25 tables in one initial migration, Alembic-generated
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_categories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_asset_category_name"),
    )
    op.create_table(
        "asset_custom_fields",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("field_type", sa.String(length=16), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("validation_rule", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_asset_custom_field_name"),
    )
    op.create_table(
        "asset_export_jobs",
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("target_format", sa.String(length=16), nullable=False),
        sa.Column("filter_criteria", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("result_storage_key", sa.String(length=1024), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_export_jobs_requested_by"),
        "asset_export_jobs",
        ["requested_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_export_jobs_status"), "asset_export_jobs", ["status"], unique=False
    )
    op.create_table(
        "asset_groups",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("group_type", sa.String(length=16), nullable=False),
        sa.Column("rule", sa.JSON(), nullable=False),
        sa.Column("member_asset_ids", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_asset_group_name"),
    )
    op.create_index(
        op.f("ix_asset_groups_group_type"), "asset_groups", ["group_type"], unique=False
    )
    op.create_table(
        "asset_import_jobs",
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("source_format", sa.String(length=16), nullable=False),
        sa.Column("source_storage_key", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("preview_only", sa.Boolean(), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("processed_rows", sa.Integer(), nullable=False),
        sa.Column("succeeded_rows", sa.Integer(), nullable=False),
        sa.Column("failed_rows", sa.Integer(), nullable=False),
        sa.Column("duplicate_rows", sa.Integer(), nullable=False),
        sa.Column("error_report", sa.JSON(), nullable=False),
        sa.Column("created_asset_ids", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rolled_back_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_import_jobs_requested_by"),
        "asset_import_jobs",
        ["requested_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_import_jobs_status"), "asset_import_jobs", ["status"], unique=False
    )
    op.create_table(
        "asset_locations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("region", sa.String(length=128), nullable=True),
        sa.Column("site", sa.String(length=128), nullable=True),
        sa.Column("building", sa.String(length=128), nullable=True),
        sa.Column("floor", sa.String(length=32), nullable=True),
        sa.Column("room", sa.String(length=64), nullable=True),
        sa.Column("rack", sa.String(length=64), nullable=True),
        sa.Column("rack_unit", sa.String(length=16), nullable=True),
        sa.Column("gps_latitude", sa.Float(), nullable=True),
        sa.Column("gps_longitude", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory_statistics",
        sa.Column("total_assets", sa.Integer(), nullable=False),
        sa.Column("total_relationships", sa.Integer(), nullable=False),
        sa.Column("type_distribution", sa.JSON(), nullable=False),
        sa.Column("health_distribution", sa.JSON(), nullable=False),
        sa.Column("lifecycle_distribution", sa.JSON(), nullable=False),
        sa.Column("os_distribution", sa.JSON(), nullable=False),
        sa.Column("vendor_distribution", sa.JSON(), nullable=False),
        sa.Column("location_distribution", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", name="uq_inventory_statistics_org"),
    )
    op.create_table(
        "asset_classes",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["asset_categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "name", name="uq_asset_class_name_per_category"),
    )
    op.create_index(
        op.f("ix_asset_classes_category_id"), "asset_classes", ["category_id"], unique=False
    )
    op.create_table(
        "asset_types",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("icon", sa.String(length=128), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["asset_categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_asset_type_code"),
    )
    op.create_index(op.f("ix_asset_types_code"), "asset_types", ["code"], unique=False)
    op.create_table(
        "inventory_assets",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("fqdn", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("mac_address", sa.String(length=64), nullable=True),
        sa.Column("serial_number", sa.String(length=128), nullable=True),
        sa.Column("vendor", sa.String(length=128), nullable=True),
        sa.Column("manufacturer", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("firmware_version", sa.String(length=64), nullable=True),
        sa.Column("operating_system", sa.String(length=128), nullable=True),
        sa.Column("architecture", sa.String(length=32), nullable=True),
        sa.Column("environment", sa.String(length=64), nullable=True),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("class_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("health", sa.String(length=16), nullable=False),
        sa.Column("lifecycle_state", sa.String(length=16), nullable=False),
        sa.Column("criticality", sa.String(length=16), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["asset_categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["class_id"], ["asset_classes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["location_id"], ["asset_locations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_assets_asset_type"), "inventory_assets", ["asset_type"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_assets_health"), "inventory_assets", ["health"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_assets_hostname"), "inventory_assets", ["hostname"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_assets_ip_address"), "inventory_assets", ["ip_address"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_assets_lifecycle_state"),
        "inventory_assets",
        ["lifecycle_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_assets_mac_address"), "inventory_assets", ["mac_address"], unique=False
    )
    op.create_index(op.f("ix_inventory_assets_name"), "inventory_assets", ["name"], unique=False)
    op.create_index(
        op.f("ix_inventory_assets_serial_number"),
        "inventory_assets",
        ["serial_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_assets_status"), "inventory_assets", ["status"], unique=False
    )
    op.create_table(
        "asset_attributes",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("custom_field_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.String(length=4096), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["custom_field_id"], ["asset_custom_fields.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "custom_field_id", name="uq_asset_attribute_field"),
    )
    op.create_index(
        op.f("ix_asset_attributes_asset_id"), "asset_attributes", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_asset_attributes_custom_field_id"),
        "asset_attributes",
        ["custom_field_id"],
        unique=False,
    )
    op.create_table(
        "asset_contacts",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("role", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_contacts_asset_id"), "asset_contacts", ["asset_id"], unique=False
    )
    op.create_table(
        "asset_discovery_links",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_asset_discovery_link_external_id"),
    )
    op.create_index(
        op.f("ix_asset_discovery_links_asset_id"),
        "asset_discovery_links",
        ["asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_discovery_links_external_id"),
        "asset_discovery_links",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_discovery_links_source"), "asset_discovery_links", ["source"], unique=False
    )
    op.create_table(
        "asset_health",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("health_status", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.String(length=2048), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_asset_health_asset_id"), "asset_health", ["asset_id"], unique=False)
    op.create_table(
        "asset_history",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_asset_history_asset_id"), "asset_history", ["asset_id"], unique=False)
    op.create_table(
        "asset_labels",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("namespace", sa.String(length=255), nullable=True),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=1024), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "namespace", "key", name="uq_asset_label_key"),
    )
    op.create_index(op.f("ix_asset_labels_asset_id"), "asset_labels", ["asset_id"], unique=False)
    op.create_table(
        "asset_lifecycle",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("previous_state", sa.String(length=16), nullable=True),
        sa.Column("new_state", sa.String(length=16), nullable=False),
        sa.Column("transitioned_by", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.String(length=1024), nullable=True),
        sa.Column("transitioned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_lifecycle_asset_id"), "asset_lifecycle", ["asset_id"], unique=False
    )
    op.create_table(
        "asset_metadata",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=4096), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "key", name="uq_asset_metadata_key"),
    )
    op.create_index(
        op.f("ix_asset_metadata_asset_id"), "asset_metadata", ["asset_id"], unique=False
    )
    op.create_table(
        "asset_owners",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("owner_type", sa.String(length=24), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "owner_type", name="uq_asset_owner_role"),
    )
    op.create_index(op.f("ix_asset_owners_asset_id"), "asset_owners", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_asset_owners_owner_type"), "asset_owners", ["owner_type"], unique=False
    )
    op.create_table(
        "asset_relationships",
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("target_asset_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=32), nullable=False),
        sa.Column("custom_label", sa.String(length=128), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["source_asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_asset_id",
            "target_asset_id",
            "relationship_type",
            name="uq_asset_relationship_edge",
        ),
    )
    op.create_index(
        op.f("ix_asset_relationships_relationship_type"),
        "asset_relationships",
        ["relationship_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_relationships_source_asset_id"),
        "asset_relationships",
        ["source_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_relationships_target_asset_id"),
        "asset_relationships",
        ["target_asset_id"],
        unique=False,
    )
    op.create_table(
        "asset_status",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=16), nullable=True),
        sa.Column("new_status", sa.String(length=16), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=1024), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_asset_status_asset_id"), "asset_status", ["asset_id"], unique=False)
    op.create_table(
        "asset_tags",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "label", name="uq_asset_tag_label"),
    )
    op.create_index(op.f("ix_asset_tags_asset_id"), "asset_tags", ["asset_id"], unique=False)
    op.create_index(op.f("ix_asset_tags_label"), "asset_tags", ["label"], unique=False)
    op.create_table(
        "asset_topology_cache",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("query_kind", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "query_kind", name="uq_asset_topology_cache_entry"),
    )
    op.create_index(
        op.f("ix_asset_topology_cache_asset_id"), "asset_topology_cache", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_asset_topology_cache_expires_at"),
        "asset_topology_cache",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "asset_versions",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_versions_asset_id"), "asset_versions", ["asset_id"], unique=False
    )
    op.create_table(
        "inventory_audit",
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=1024), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["inventory_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_audit_asset_id"), "inventory_audit", ["asset_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:  # noqa: PLR0915 -- 25 tables in one initial migration, Alembic-generated
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_audit_asset_id"), table_name="inventory_audit")
    op.drop_table("inventory_audit")
    op.drop_index(op.f("ix_asset_versions_asset_id"), table_name="asset_versions")
    op.drop_table("asset_versions")
    op.drop_index(op.f("ix_asset_topology_cache_expires_at"), table_name="asset_topology_cache")
    op.drop_index(op.f("ix_asset_topology_cache_asset_id"), table_name="asset_topology_cache")
    op.drop_table("asset_topology_cache")
    op.drop_index(op.f("ix_asset_tags_label"), table_name="asset_tags")
    op.drop_index(op.f("ix_asset_tags_asset_id"), table_name="asset_tags")
    op.drop_table("asset_tags")
    op.drop_index(op.f("ix_asset_status_asset_id"), table_name="asset_status")
    op.drop_table("asset_status")
    op.drop_index(op.f("ix_asset_relationships_target_asset_id"), table_name="asset_relationships")
    op.drop_index(op.f("ix_asset_relationships_source_asset_id"), table_name="asset_relationships")
    op.drop_index(
        op.f("ix_asset_relationships_relationship_type"), table_name="asset_relationships"
    )
    op.drop_table("asset_relationships")
    op.drop_index(op.f("ix_asset_owners_owner_type"), table_name="asset_owners")
    op.drop_index(op.f("ix_asset_owners_asset_id"), table_name="asset_owners")
    op.drop_table("asset_owners")
    op.drop_index(op.f("ix_asset_metadata_asset_id"), table_name="asset_metadata")
    op.drop_table("asset_metadata")
    op.drop_index(op.f("ix_asset_lifecycle_asset_id"), table_name="asset_lifecycle")
    op.drop_table("asset_lifecycle")
    op.drop_index(op.f("ix_asset_labels_asset_id"), table_name="asset_labels")
    op.drop_table("asset_labels")
    op.drop_index(op.f("ix_asset_history_asset_id"), table_name="asset_history")
    op.drop_table("asset_history")
    op.drop_index(op.f("ix_asset_health_asset_id"), table_name="asset_health")
    op.drop_table("asset_health")
    op.drop_index(op.f("ix_asset_discovery_links_source"), table_name="asset_discovery_links")
    op.drop_index(op.f("ix_asset_discovery_links_external_id"), table_name="asset_discovery_links")
    op.drop_index(op.f("ix_asset_discovery_links_asset_id"), table_name="asset_discovery_links")
    op.drop_table("asset_discovery_links")
    op.drop_index(op.f("ix_asset_contacts_asset_id"), table_name="asset_contacts")
    op.drop_table("asset_contacts")
    op.drop_index(op.f("ix_asset_attributes_custom_field_id"), table_name="asset_attributes")
    op.drop_index(op.f("ix_asset_attributes_asset_id"), table_name="asset_attributes")
    op.drop_table("asset_attributes")
    op.drop_index(op.f("ix_inventory_assets_status"), table_name="inventory_assets")
    op.drop_index(op.f("ix_inventory_assets_serial_number"), table_name="inventory_assets")
    op.drop_index(op.f("ix_inventory_assets_name"), table_name="inventory_assets")
    op.drop_index(op.f("ix_inventory_assets_mac_address"), table_name="inventory_assets")
    op.drop_index(op.f("ix_inventory_assets_lifecycle_state"), table_name="inventory_assets")
    op.drop_index(op.f("ix_inventory_assets_ip_address"), table_name="inventory_assets")
    op.drop_index(op.f("ix_inventory_assets_hostname"), table_name="inventory_assets")
    op.drop_index(op.f("ix_inventory_assets_health"), table_name="inventory_assets")
    op.drop_index(op.f("ix_inventory_assets_asset_type"), table_name="inventory_assets")
    op.drop_table("inventory_assets")
    op.drop_index(op.f("ix_asset_types_code"), table_name="asset_types")
    op.drop_table("asset_types")
    op.drop_index(op.f("ix_asset_classes_category_id"), table_name="asset_classes")
    op.drop_table("asset_classes")
    op.drop_table("inventory_statistics")
    op.drop_table("asset_locations")
    op.drop_index(op.f("ix_asset_import_jobs_status"), table_name="asset_import_jobs")
    op.drop_index(op.f("ix_asset_import_jobs_requested_by"), table_name="asset_import_jobs")
    op.drop_table("asset_import_jobs")
    op.drop_index(op.f("ix_asset_groups_group_type"), table_name="asset_groups")
    op.drop_table("asset_groups")
    op.drop_index(op.f("ix_asset_export_jobs_status"), table_name="asset_export_jobs")
    op.drop_index(op.f("ix_asset_export_jobs_requested_by"), table_name="asset_export_jobs")
    op.drop_table("asset_export_jobs")
    op.drop_table("asset_custom_fields")
    op.drop_table("asset_categories")
    # ### end Alembic commands ###
