"""Workflow SDK constants.

Per docs/028_Enterprise_Workflow_SDK.md.txt. Default timing, retry,
and safety-bound values every workflow inherits unless it overrides
them.
"""

from __future__ import annotations

DEFAULT_TASK_TIMEOUT_SECONDS = 300.0
DEFAULT_WORKFLOW_TIMEOUT_SECONDS = 3600.0
DEFAULT_APPROVAL_TIMEOUT_SECONDS = 86400.0

DEFAULT_RETRY_MAX_ATTEMPTS = 3
DEFAULT_CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
DEFAULT_CIRCUIT_BREAKER_RECOVERY_SECONDS = 30.0

DEFAULT_CHECKPOINT_INTERVAL_SECONDS = 30.0

DEFAULT_MAX_PARALLEL_BRANCHES = 10
DEFAULT_LOOP_MAX_ITERATIONS = 10_000
DEFAULT_MAX_DAG_NODES = 1_000

DEFAULT_SOURCE_SERVICE = "workflow-engine"

__all__ = [
    "DEFAULT_APPROVAL_TIMEOUT_SECONDS",
    "DEFAULT_CHECKPOINT_INTERVAL_SECONDS",
    "DEFAULT_CIRCUIT_BREAKER_FAILURE_THRESHOLD",
    "DEFAULT_CIRCUIT_BREAKER_RECOVERY_SECONDS",
    "DEFAULT_LOOP_MAX_ITERATIONS",
    "DEFAULT_MAX_DAG_NODES",
    "DEFAULT_MAX_PARALLEL_BRANCHES",
    "DEFAULT_RETRY_MAX_ATTEMPTS",
    "DEFAULT_SOURCE_SERVICE",
    "DEFAULT_TASK_TIMEOUT_SECONDS",
    "DEFAULT_WORKFLOW_TIMEOUT_SECONDS",
]
