"""initial validation schema

Revision ID: c20173953975
Revises: 
Create Date: 2026-07-27 19:40:54.877147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20173953975'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_audit',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validation_type', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_categories_name'), 'validation_categories', ['name'], unique=False)
    op.create_index(op.f('ix_validation_categories_validation_type'), 'validation_categories', ['validation_type'], unique=False)
    op.create_table('validation_profiles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_type', sa.String(length=24), nullable=False),
    sa.Column('target_types', sa.JSON(), nullable=False),
    sa.Column('check_ids', sa.JSON(), nullable=False),
    sa.Column('concurrency_strategy', sa.String(length=16), nullable=False),
    sa.Column('scoring_weights', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('current_version_number', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_profiles_name'), 'validation_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_validation_profiles_profile_type'), 'validation_profiles', ['profile_type'], unique=False)
    op.create_table('validation_statistics',
    sa.Column('total_profiles', sa.Integer(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('average_duration_seconds', sa.Float(), nullable=False),
    sa.Column('top_failures', sa.JSON(), nullable=False),
    sa.Column('trend_data', sa.JSON(), nullable=False),
    sa.Column('asset_health_trends', sa.JSON(), nullable=False),
    sa.Column('compliance_trends', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_targets',
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_targets_external_id'), 'validation_targets', ['external_id'], unique=False)
    op.create_index(op.f('ix_validation_targets_name'), 'validation_targets', ['name'], unique=False)
    op.create_index(op.f('ix_validation_targets_target_type'), 'validation_targets', ['target_type'], unique=False)
    op.create_table('validation_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_type', sa.String(length=24), nullable=False),
    sa.Column('template_content', sa.JSON(), nullable=False),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('authored_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_templates_name'), 'validation_templates', ['name'], unique=False)
    op.create_index(op.f('ix_validation_templates_profile_type'), 'validation_templates', ['profile_type'], unique=False)
    op.create_table('validation_checks',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('check_type', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collector_key', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['validation_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_checks_category_id'), 'validation_checks', ['category_id'], unique=False)
    op.create_index(op.f('ix_validation_checks_check_type'), 'validation_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_validation_checks_name'), 'validation_checks', ['name'], unique=False)
    op.create_table('validation_executions',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('target_ids', sa.JSON(), nullable=False),
    sa.Column('trigger_type', sa.String(length=24), nullable=False),
    sa.Column('concurrency_strategy', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['validation_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_executions_profile_id'), 'validation_executions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_validation_executions_status'), 'validation_executions', ['status'], unique=False)
    op.create_table('validation_history',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['validation_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['validation_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_history_execution_id'), 'validation_history', ['execution_id'], unique=False)
    op.create_index(op.f('ix_validation_history_status'), 'validation_history', ['status'], unique=False)
    op.create_index(op.f('ix_validation_history_target_id'), 'validation_history', ['target_id'], unique=False)
    op.create_table('validation_reports',
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('report_type', sa.String(length=24), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['validation_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_reports_execution_id'), 'validation_reports', ['execution_id'], unique=False)
    op.create_index(op.f('ix_validation_reports_report_type'), 'validation_reports', ['report_type'], unique=False)
    op.create_table('validation_rules',
    sa.Column('check_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('result_status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('remediation_hint', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['validation_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_rules_check_id'), 'validation_rules', ['check_id'], unique=False)
    op.create_index(op.f('ix_validation_rules_name'), 'validation_rules', ['name'], unique=False)
    op.create_table('validation_scores',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('infrastructure_score', sa.Float(), nullable=True),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('configuration_score', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['validation_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_scores_execution_id'), 'validation_scores', ['execution_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('check_id', sa.Uuid(), nullable=False),
    sa.Column('check_type', sa.String(length=24), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['validation_checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['validation_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['validation_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_check_id'), 'validation_results', ['check_id'], unique=False)
    op.create_index(op.f('ix_validation_results_execution_id'), 'validation_results', ['execution_id'], unique=False)
    op.create_index(op.f('ix_validation_results_rule_id'), 'validation_results', ['rule_id'], unique=False)
    op.create_index(op.f('ix_validation_results_status'), 'validation_results', ['status'], unique=False)
    op.create_index(op.f('ix_validation_results_target_id'), 'validation_results', ['target_id'], unique=False)
    op.create_table('validation_failures',
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['validation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_failures_is_resolved'), 'validation_failures', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_validation_failures_result_id'), 'validation_failures', ['result_id'], unique=False)
    op.create_index(op.f('ix_validation_failures_severity'), 'validation_failures', ['severity'], unique=False)
    op.create_table('validation_result_details',
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['validation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_result_details_key'), 'validation_result_details', ['key'], unique=False)
    op.create_index(op.f('ix_validation_result_details_result_id'), 'validation_result_details', ['result_id'], unique=False)
    op.create_table('validation_exceptions',
    sa.Column('failure_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['failure_id'], ['validation_failures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_exceptions_failure_id'), 'validation_exceptions', ['failure_id'], unique=False)
    op.create_index(op.f('ix_validation_exceptions_status'), 'validation_exceptions', ['status'], unique=False)
    op.create_table('validation_remediation',
    sa.Column('failure_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('automation_job_key', sa.String(length=255), nullable=True),
    sa.Column('playbook_key', sa.String(length=255), nullable=True),
    sa.Column('workflow_key', sa.String(length=255), nullable=True),
    sa.Column('knowledge_base_url', sa.String(length=2048), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['failure_id'], ['validation_failures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_remediation_action_type'), 'validation_remediation', ['action_type'], unique=False)
    op.create_index(op.f('ix_validation_remediation_failure_id'), 'validation_remediation', ['failure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_remediation_failure_id'), table_name='validation_remediation')
    op.drop_index(op.f('ix_validation_remediation_action_type'), table_name='validation_remediation')
    op.drop_table('validation_remediation')
    op.drop_index(op.f('ix_validation_exceptions_status'), table_name='validation_exceptions')
    op.drop_index(op.f('ix_validation_exceptions_failure_id'), table_name='validation_exceptions')
    op.drop_table('validation_exceptions')
    op.drop_index(op.f('ix_validation_result_details_result_id'), table_name='validation_result_details')
    op.drop_index(op.f('ix_validation_result_details_key'), table_name='validation_result_details')
    op.drop_table('validation_result_details')
    op.drop_index(op.f('ix_validation_failures_severity'), table_name='validation_failures')
    op.drop_index(op.f('ix_validation_failures_result_id'), table_name='validation_failures')
    op.drop_index(op.f('ix_validation_failures_is_resolved'), table_name='validation_failures')
    op.drop_table('validation_failures')
    op.drop_index(op.f('ix_validation_results_target_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_status'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_rule_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_execution_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_check_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_validation_scores_execution_id'), table_name='validation_scores')
    op.drop_table('validation_scores')
    op.drop_index(op.f('ix_validation_rules_name'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_check_id'), table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_validation_reports_report_type'), table_name='validation_reports')
    op.drop_index(op.f('ix_validation_reports_execution_id'), table_name='validation_reports')
    op.drop_table('validation_reports')
    op.drop_index(op.f('ix_validation_history_target_id'), table_name='validation_history')
    op.drop_index(op.f('ix_validation_history_status'), table_name='validation_history')
    op.drop_index(op.f('ix_validation_history_execution_id'), table_name='validation_history')
    op.drop_table('validation_history')
    op.drop_index(op.f('ix_validation_executions_status'), table_name='validation_executions')
    op.drop_index(op.f('ix_validation_executions_profile_id'), table_name='validation_executions')
    op.drop_table('validation_executions')
    op.drop_index(op.f('ix_validation_checks_name'), table_name='validation_checks')
    op.drop_index(op.f('ix_validation_checks_check_type'), table_name='validation_checks')
    op.drop_index(op.f('ix_validation_checks_category_id'), table_name='validation_checks')
    op.drop_table('validation_checks')
    op.drop_index(op.f('ix_validation_templates_profile_type'), table_name='validation_templates')
    op.drop_index(op.f('ix_validation_templates_name'), table_name='validation_templates')
    op.drop_table('validation_templates')
    op.drop_index(op.f('ix_validation_targets_target_type'), table_name='validation_targets')
    op.drop_index(op.f('ix_validation_targets_name'), table_name='validation_targets')
    op.drop_index(op.f('ix_validation_targets_external_id'), table_name='validation_targets')
    op.drop_table('validation_targets')
    op.drop_table('validation_statistics')
    op.drop_index(op.f('ix_validation_profiles_profile_type'), table_name='validation_profiles')
    op.drop_index(op.f('ix_validation_profiles_name'), table_name='validation_profiles')
    op.drop_table('validation_profiles')
    op.drop_index(op.f('ix_validation_categories_validation_type'), table_name='validation_categories')
    op.drop_index(op.f('ix_validation_categories_name'), table_name='validation_categories')
    op.drop_table('validation_categories')
    op.drop_table('validation_audit')
    # ### end Alembic commands ###
