"""add username to automation_targets

Revision ID: a6462780f7fe
Revises: 2c545f8d08d3
Create Date: 2026-07-25 13:58:18.603361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6462780f7fe'
down_revision: Union[str, Sequence[str], None] = '2c545f8d08d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_targets', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automation_targets', 'username')
    # ### end Alembic commands ###
