"""AI narrative sections, via the AI Assistant Service ("AI REPORTING").

Integrates Prompt 046 rather than re-implementing model access: that
service already owns provider credentials, fallback, guardrails, and
grounding, and duplicating any of it here would mean two places to keep
correct.

Every summary is generated by ``POST /ai/reports``, which returns prose
plus the citations it was grounded in. The citations are carried into
the rendered section so a reader can check what the narrative was based
on -- an unattributed AI paragraph in a compliance report is worse than
no paragraph at all.

**AI sections never fail a report.** If the assistant is unreachable or
returns nothing usable, the section is marked unavailable and the rest
of the report is delivered. A capacity report whose numbers are correct
is still worth having when the prose summary is missing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any
from uuid import UUID

import httpx
from shared_core.exceptions.dependency import DependencyError
from shared_core.logging.logger import get_logger

logger = get_logger("app.ai.summaries")

AI_REPORT_TYPE = "natural_language"
"""The AI Assistant's own report type for free-form prose.

Every AI section here asks a question in its own words, so the
narrative type is the right one; the specific framing (executive,
trend, root cause, risk) is carried in the instruction text rather than
by switching report type, which keeps the contract with Prompt 046 to
a single shape.
"""

_MAX_CONTEXT_ROWS = 50
_MAX_CONTEXT_CHARS = 6_000


@dataclass(frozen=True, slots=True)
class AiSummary:
    """One generated narrative and what it was grounded in."""

    text: str
    citations: list[dict[str, Any]] = field(default_factory=list)


def build_context(rows: list[dict[str, Any]], *, limit: int = _MAX_CONTEXT_ROWS) -> str:
    """Render sampled rows as compact context for the model.

    Bounded twice -- by row count and by total characters -- because
    the assistant charges by token and a 50,000-row report would
    produce a prompt no provider would accept anyway. Sampling the head
    is honest and stated in the prompt itself.
    """
    if not rows:
        return ""
    sampled = rows[:limit]
    lines: list[str] = []
    used = 0
    for row in sampled:
        line = "; ".join(
            f"{key}={value}" for key, value in sorted(row.items()) if value is not None
        )
        if used + len(line) > _MAX_CONTEXT_CHARS:
            break
        lines.append(f"- {line}")
        used += len(line)
    if len(rows) > len(lines):
        lines.append(f"(showing {len(lines)} of {len(rows)} rows)")
    return "\n".join(lines)


class AiSummaryClient:
    """Generates report narratives through the AI Assistant Service."""

    def __init__(
        self,
        client: httpx.AsyncClient,
        *,
        base_url: str,
        caller_token: str,
        enabled: bool = True,
    ) -> None:
        self._client = client
        self._base_url = base_url.rstrip("/")
        self._caller_token = caller_token
        self._enabled = enabled

    @property
    def enabled(self) -> bool:
        """Whether AI sections are configured on this deployment."""
        return self._enabled

    async def summarise(
        self,
        *,
        organization_id: UUID,
        instruction: str,
        context: str = "",
        project_id: UUID | None = None,
    ) -> AiSummary:
        """Generate one narrative.

        Raises:
            DependencyError: If AI reporting is disabled, or the
                assistant is unreachable or refuses the request. The
                renderer catches this and marks the section unavailable
                rather than failing the whole report.
        """
        if not self._enabled:
            raise DependencyError("AI reporting is disabled on this deployment.")

        subject = instruction if not context else f"{instruction}\n\nData:\n{context}"
        payload: dict[str, Any] = {
            "organization_id": str(organization_id),
            "report_type": AI_REPORT_TYPE,
            "subject": subject,
        }
        if project_id is not None:
            payload["project_id"] = str(project_id)

        try:
            response = await self._client.post(
                f"{self._base_url}/ai/reports",
                json=payload,
                headers={"Authorization": f"Bearer {self._caller_token}"},
            )
        except httpx.HTTPError as exc:
            raise DependencyError(f"ai-assistant-service is unreachable: {exc}") from exc

        if response.status_code not in (httpx.codes.OK, httpx.codes.CREATED):
            raise DependencyError(
                f"ai-assistant-service returned HTTP {response.status_code} for a report summary."
            )

        try:
            body = response.json()
        except ValueError as exc:
            raise DependencyError("ai-assistant-service returned a non-JSON body.") from exc

        data = body.get("data") or {}
        text = str(data.get("body") or "").strip()
        if not text:
            raise DependencyError("ai-assistant-service returned an empty summary.")

        citations = data.get("citations") or []
        return AiSummary(
            text=text,
            citations=[entry for entry in citations if isinstance(entry, dict)],
        )


__all__ = ["AI_REPORT_TYPE", "AiSummary", "AiSummaryClient", "build_context"]
