"""Connector SDK constants.

Per docs/027_Enterprise_Connector_SDK.md.txt. Default timing, pooling,
and retry/circuit-breaker values every connector inherits unless it
overrides them.
"""

from __future__ import annotations

DEFAULT_CONNECT_TIMEOUT_SECONDS = 10.0
DEFAULT_COMMAND_TIMEOUT_SECONDS = 30.0
DEFAULT_TRANSFER_TIMEOUT_SECONDS = 120.0

DEFAULT_POOL_MIN_SIZE = 1
DEFAULT_POOL_MAX_SIZE = 10
DEFAULT_POOL_ACQUIRE_TIMEOUT_SECONDS = 30.0

DEFAULT_SESSION_IDLE_TIMEOUT_SECONDS = 300.0
DEFAULT_SESSION_MAX_LIFETIME_SECONDS = 3600.0

DEFAULT_KEEPALIVE_INTERVAL_SECONDS = 30.0

DEFAULT_RETRY_MAX_ATTEMPTS = 3
DEFAULT_CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
DEFAULT_CIRCUIT_BREAKER_RECOVERY_SECONDS = 30.0

DEFAULT_RATE_LIMIT_PER_SECOND = 10
DEFAULT_RATE_LIMIT_BURST = 20

DEFAULT_HEALTH_CHECK_TIMEOUT_SECONDS = 5.0

__all__ = [
    "DEFAULT_CIRCUIT_BREAKER_FAILURE_THRESHOLD",
    "DEFAULT_CIRCUIT_BREAKER_RECOVERY_SECONDS",
    "DEFAULT_COMMAND_TIMEOUT_SECONDS",
    "DEFAULT_CONNECT_TIMEOUT_SECONDS",
    "DEFAULT_HEALTH_CHECK_TIMEOUT_SECONDS",
    "DEFAULT_KEEPALIVE_INTERVAL_SECONDS",
    "DEFAULT_POOL_ACQUIRE_TIMEOUT_SECONDS",
    "DEFAULT_POOL_MAX_SIZE",
    "DEFAULT_POOL_MIN_SIZE",
    "DEFAULT_RATE_LIMIT_BURST",
    "DEFAULT_RATE_LIMIT_PER_SECOND",
    "DEFAULT_RETRY_MAX_ATTEMPTS",
    "DEFAULT_SESSION_IDLE_TIMEOUT_SECONDS",
    "DEFAULT_SESSION_MAX_LIFETIME_SECONDS",
    "DEFAULT_TRANSFER_TIMEOUT_SECONDS",
]
